### ISSUE TITLE
Error on double-click for annotations listed in the second page of the annotation dataGrid

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1459] opened 2017-01-25 21:32 UTC
When performing a double-click on an annotation that is shown on the 2nd (or any subsequent page) of the dataGrid, the gene feature fails to expand to show its transcripts. Clicking on the '+' sign to list the transcripts still works.

The error observed on console at the time of double-click:
```
Uncaught es__gwt$backingJsError: Error: Exception caught: Row index: -20, Row size: 24
    at Uh.Rh [as Hb] (annotator-0.js:3234:31)
    at Ih (annotator-0.js:830:26)
    at mg (annotator-0.js:1453:25)
    at es.qg (annotator-0.js:1452:36)
    at es.wg (annotator-0.js:987:21)
    at es.bs (annotator-0.js:1636:19)
    at es (annotator-0.js:700:19)
    at Fr (annotator-0.js:2818:110)
    at gV (annotator-0.js:1076:26)
    at kp (annotator-0.js:2791:144)
    at iV (annotator-0.js:2570:110)
    at NY.XV [as Nc] (annotator-0.js:3235:12608)
    at g_ (annotator-0.js:2331:78)
    at HTMLDivElement.M0 (annotator-0.js:2152:44)
    at bh (annotator-0.js:1479:29)
    at fh (annotator-0.js:1995:44)
    at HTMLDivElement.eval (annotator-0.js:2629:50)a: Qrbe: aibf: "Exception caught: Row index: -20, Row size: 24"g: null__proto__: Object
```

**Comment by nathandunn** [comment] 2017-01-25 22:29
The problem is that when you use the selection-model it uses the keyboard selected row, which ignores pagination.   Now counting pagination and page size.  Thanks for catching this @deepakunni3

**Comment by monicacecilia** [comment] 2017-01-31 22:59
There is one unwanted behaviour here, though. When double-clicking on the child object (e.g. transcript) of the annotation listed in the 'Annotations' tab, under 'Name', the expanded annotation collapses back. Of course, this is not the case for those genomic elements without children annotations (e.g. repetitive regions, TEs). 

It only happens to the annotation that the curator is navigating to. The other children annotations remain expanded. 

To reproduce: 
1. Double click on the 'Name' of an annotation from the list in the 'Annotations' tab. 
2. Double click on the the child annotation (e.g. transcript)
3. Result: Apollo will navigate to the location of that child annotation, but the child annotation will be collapsed back and only parent annotation is visible.

**Comment by monicacecilia** [comment] 2017-01-31 23:03
I should clarify, this is independent of pagination. Added report here because it is related to expansion / collapse of child annotations.

**Comment by nathandunn** [comment] 2017-01-31 23:53
@monicacecilia  To clarify.  Keep the behavior, but don't close the child on double-click.   Yeah, that makes sense.

**Comment by monicacecilia** [comment] 2017-01-31 23:57
@nathandunn  Correct. Keep the behaviour, but don't collapse child on double-click.

**Comment by nathandunn** [comment] 2017-02-01 01:08
@monicacecilia  I remember why I didn't do this.  Its a pain in the ass.  The click goes to the entire row, so I can't really tell whether the gene or the transcript was selected (easily).

I'll think if there is a workaround.  I'm going to open a new bug so its a bit easier to track.

**Comment by nathandunn** [comment] 2017-02-01 01:09
Closing in favor of #1467

**Closed by nathandunn** 2017-02-01 01:09 UTC
Labels: bug, in progress
