### ISSUE TITLE
No record of feature deletion

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#11] opened 2014-04-29 12:08 UTC
Could you add a trigger to log when a user deletes an annotation?  Ideally it would have the id for the deleter, the locus of the feature and the creator of the deleted feature.  If this is just a tab-delimited text file in the directory it would be great.  If it was viewable for admins through the admin menu it would be even better.

**Comment by nathandunn** [comment] 2015-08-07 16:30
This is related to the #488.    Its possible I'm not recording it, but would not be hard to add.

**Comment by nathandunn** [comment] 2016-11-19 06:49
dupe of #1257

**Closed by nathandunn** 2016-11-19 06:49 UTC
Labels: enhancement
