### ISSUE TITLE
Extract arbitrary sequence regions from genome

### ISSUE THREAD

**Issue by aselawsd** [GMOD/Apollo#1165] opened 2016-07-05 16:57 UTC
For manual annotation it would be great if arbitrary regions (within or between transcripts) can be extracted from the genome for further analysis. Ideally user should be able to highlight the region of interest on the reference sequence and right click and extract.

example - Extract 5' UTR region preceding an annotated transcript to check for RNA structure or promoters.

**Comment by nathandunn** [comment] 2016-07-05 17:15
@aselawsd  does 

#1154 / #1152 provide the functionality you want?   I was going to have @monicacecilia  review this as well.

**Comment by nathandunn** [comment] 2016-07-05 17:22
Closed as dupe of #1152

**Comment by nathandunn** [comment] 2016-07-05 17:23
@aselawsd Do you want to test this in the master, or can you wait for this to be further reviewed?

**Closed by nathandunn** 2016-07-05 17:22 UTC

**Comment by aselawsd** [comment] 2016-07-05 17:33
I am in no hurry. Please put the fix through your normal testing and
approval/review process
