### ISSUE TITLE
Update or Save button on the add organism panel 2.x

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#277] opened 2015-04-15 13:50 UTC
Currently there are two buttons on the organism panel, one to add a new organism and one to delete the currently selected organism.  Could you add a button to update or save an organism if there is a state change (e.g. a blat database needs to be updated to non hard masked version).

**Comment by cmdcolin** [comment] 2015-04-15 14:45
I would prefer a save button like this too. Technically the value is autoupdated once you click away from the field (similar to the information editor in this respect) but i like having save buttons :+1:

**Comment by childers** [comment] 2015-04-15 14:50
Thanks! The reason I asked was because it was not saving the information in the Blat database field.  I added the org, then went back to add the blat db. We're testing this on our local dev environment, and I confirmed with Gary that we pulled the updates earlier this morning.  Can you check this on your version?

**Comment by nathandunn** [comment] 2015-04-15 14:54
Colin,

Moni gave similar feedback about the User and Group boxes (i.e., its confusing to hit “new” and then hit “save”) and so I switched the behavior as follows:

- If no user is selected, “save” creates a new user if you fill in the info
- If a user is selected any change automatically updates the user
- If a user is selected a “delete” button will show up.  

Could probably do something similar for the Organism (realize it was my fault for coding it wrong in the first place).

Nathan

**Comment by cmdcolin** [comment] 2015-04-16 16:00
Currently I am seeing these errors when updating any particular field in the organism panel from the console.log in javascript

    Uncaught com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'ordinal_3_g$' of undefined
    castFireEvent_0_g$ @ EventBus.java:69
    fireEvent_3_g$ @ SimpleEventBus.java:57
    onResponseReceived_19_g$ @ OrganismRestService.java:118
    fireOnResponseReceived_0_g$ @ Request.java:250
    onReadyStateChange_0_g$ @ RequestBuilder.java:412

Seems to implicate the OrganismRestService

Not sure if this is related to the blat field not updating since even updating name produces this, however the name updating works.

In other related causes I have the UiHandler on the blatdb field so it should ideally be updating

**Comment by cmdcolin** [comment] 2015-04-21 17:28
Should be ready

**Comment by nathandunn** [comment] 2015-04-21 17:41
@cmdcolin   Thanks.  I'll send it over when I get a chance.

**Comment by nathandunn** [comment] 2015-04-21 18:07
@cmdcolin   When there are no selected organisms, you should clear the edit mode for the last-selected organism.    Should be a quick fix.

**Comment by cmdcolin** [comment] 2015-04-21 18:11
Can you clarify?

**Comment by nathandunn** [comment] 2015-04-21 18:17
@cmdcolin   Here is the clarification:

Correct edit behavior:

![screen shot 2015-04-21 at 11 12 57 am](https://cloud.githubusercontent.com/assets/751274/7259374/a47ffbe0-e817-11e4-9af2-f08d97ff52f8.png)

Incorrect, should not be in edit mode if nothing selected:

![screen shot 2015-04-21 at 11 13 02 am](https://cloud.githubusercontent.com/assets/751274/7259378/ad1c0280-e817-11e4-8c12-4885fadb4247.png)

Expect this.  I get this when I create an organism and then cancel:

![screen shot 2015-04-21 at 11 13 12 am](https://cloud.githubusercontent.com/assets/751274/7259400/d1a5445e-e817-11e4-88ed-f957f89181b4.png)

**Comment by cmdcolin** [comment] 2015-04-27 23:16
I can't reproduce this state where no organism is selected.

You said this is created when you create an organism and then hit cancel?

**Comment by nathandunn** [comment] 2015-04-27 23:50
So the FIRST image is:
1 - select an organism on the organism tab
2 - deselect an organism on the organism tab
(I also get this when I move away from the organism tab and come back)

However, I want the deselection screen to look like the SECOND image, which is created by:
1 - select the "Add New Organism Button"
2 - hit the "Cancel" button
(I also get this when I reload the page and I'm on the Organism tab)

Basically in OrganismPanel, you need to handle the singleSelectionModel better.  It looks like it is only handling the case where objects are selected, but not deselected.  

        singleSelectionModel.addSelectionChangeHandler(new SelectionChangeEvent.Handler() {
            @Override
            public void onSelectionChange(SelectionChangeEvent event) {
                if (singleSelectionModel.getSelectedObject() != null) {
                    setSelectedInfo(singleSelectionModel.getSelectedObject());
                    setDefaultButtonState(singleSelectionModel.getSelectedObject() != null);
                }
            }
        });

**Comment by cmdcolin** [comment] 2015-04-28 00:19
>deselect an organism on the organism tab

Sorry if i'm being dense but how do you deselect an organism?

**Comment by nathandunn** [comment] 2015-04-28 01:23
No worries.   

I usually do a command-click.   The same way you do a multi-select.  

Nathan

**Comment by cmdcolin** [comment] 2015-04-28 14:55
That particular deselection bug should be fixed (and the original issue as well, although now values are auto-updated instead of through a save button)

**Comment by nathandunn** [comment] 2015-04-28 16:00
The behavior I want works now.   However, when you hit “add new organism” it stays on the “unselected” screen (all of the fields are un-editable). 

You can look at the way the user and groups tabs are done.  Groups is very simple, where user is basically the same model.  

Nathan

**Comment by cmdcolin** [comment] 2015-04-28 16:52
Interesting. I think that is an unintended consequence of the "deselect" thing that I added today being called when the selecter is cleared programmatically

**Comment by cmdcolin** [comment] 2015-04-28 17:43
@nathandunn That particular problem is fixed

**Comment by nathandunn** [comment] 2015-04-28 18:10
@cmdcolin   Looks good . . .

**Comment by monicacecilia** [comment] 2015-05-01 22:51
I tested and can confirm that the information is being saved as I type it, although there is not a prompt or "Save" button as the issue originally requested. So here only the "update" part is true. It's working!

**Closed by monicacecilia** 2015-05-01 22:51 UTC
Labels: enhancement, Ready
