### ISSUE TITLE
Overlapper code is not working in some cases (?)

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#528] opened 2015-08-07 20:37 UTC
I was just testing some behaviors in 2.0.0 RC4 such as creating new annotations from single exons and from individual RNA-seq reads and I wanted to check that they were being added to the same gene with the OrfOverlapper code.

From what I can tell though, it appears in many cases that they are not added to the same gene and it might be due to the OrfOverlapper code not working correctly(?).  I have not dug into the issue very much, but it simply seemed to me, behavior wise, that these should all be the same gene

Attached is a figure showing the different genes that were created all from dragged and dropped annotation evidence that is essentially the same gene (I tested dragging multiple reads, dragging single exons, flipping the orientation of the transcript after dropping on annotation track, etc) 

![test2](https://cloud.githubusercontent.com/assets/6511937/9145463/306477c4-3d1a-11e5-9625-551c8becf4b2.png)

**Comment by cmdcolin** [comment] 2015-08-07 20:40
The colored circles in my image all represent a different genes that were created from the dragged and dropped evidence. The gene groups were determined by going into the "Edit Information" dialog and looking at which transcripts were in the dropdown box for that gene.

**Comment by nathandunn** [comment] 2015-08-07 21:23
This is a dupe of #498 scheduled for 2.0.1 . . . Its because it calculates the overlapping phase based on the exon start (?) instead of the CDS start.

**Comment by nathandunn** [comment] 2015-08-07 21:24
Also related to #73.

**Closed by nathandunn** 2015-08-07 21:23 UTC

**Comment by cmdcolin** [comment] 2015-08-07 21:27
Sounds about right. I was looking for those issues but wasnt finding them
