### ISSUE TITLE
Plugin stub not found

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#2055] opened 2019-02-18 15:02 UTC
Hi,
I'm trying to update my docker image from 2.1.0 to 2.3.0, and I get this JBrowse error:

`Plugin stub not found, please ensure the plugin was included in this JBrowse build.`

My dockerfile is there: https://github.com/abretaud/docker-apollo/tree/bipaa
I had a few plugins in my [apollo-config.groovy](https://github.com/abretaud/docker-apollo/blob/bipaa/apollo-config.groovy#L122), I guess that's the problem?

I tried with 2.2.0 and I didn't get this problem

Any thoughts?

**Comment by abretaud** [comment] 2019-02-18 15:39
I guess it comes from this commit: https://github.com/abretaud/Apollo/commit/39678d6c605c3c336f49d959a5458bf0e279c1ba#diff-2fd45819f7cf7c70bbdc718d5b19faefR463

**Comment by nathandunn** [comment] 2019-02-18 15:44
@abretaud  Do you have the trackList.json or tracks.conf you used?  

This fixed a larger underlying problem, but it will die if the plugin is incorrectly declared in `trackList.conf`.

**Comment by abretaud** [comment] 2019-02-18 15:52
It's with a jbrowse data dir generated with the Galaxy tool. The trackList.json looks like this:

```
{
   "formatVersion" : 1,
   "hideGenomeOptions" : false,
   "names" : {
      "type" : "Hash",
      "url" : "names/"
   },
   "plugins" : [
      {
         "location" : "https://cdn.rawgit.com/TAMU-CPT/blastview/97572a21b7f011c2b4d9a0b5af40e292d694cbef/",
         "name" : "BlastView"
      }
   ],
   "shareLink" : true,
   "show_menu" : true,
   "show_nav" : true,
   "show_overview" : true,
   "show_tracklist" : true,
[...More stuff......]
```
Commenting the `plugins` block is enough to make jbrowse load completely.

(by the way, with the update to apollo 2.3, is it recommended to switch to neatfeatures or not yet?)

**Comment by nathandunn** [comment] 2019-02-18 16:12
Okay, that fix makes sense.  Can you move the plugin to Apollo directly?   

I think there might be a workaround in there if you leave it (an empty value, or just defining a sing plugin . . can't remember).   

Yes, 2.3 is all NeatFeatures.

**Comment by abretaud** [comment] 2019-02-18 16:20
Do you mean in apollo-config.groovy? It's already there: https://github.com/abretaud/docker-apollo/blob/bipaa/apollo-config.groovy#L144

**Comment by nathandunn** [comment] 2019-02-18 16:23
Oh, so is the fix of removing it from trackList.json sufficient to close this (though we can leave this open as a sign-post)? 

Also, was planning on releasing 2.3.1 today after I test the RC.

**Comment by abretaud** [comment] 2019-02-18 16:26
It could be enough BUT if we don't have the plugin defined in trackList.json, we can't use the jbrowse data dir outside of Apollo (like in galaxy, or in an independent jbrowse instance elsewhere). So that's not really usable for me :/ Should I try removing it from 
apollo-config.groovy?

**Comment by nathandunn** [comment] 2019-02-18 17:37
Yes, I would try removing it from the `apollo-config.groovy` . .. let me know whether or not that works.  

If not, I can look for a fix a bit later today.

**Comment by nathandunn** [comment] 2019-02-18 23:11
The original reason for the fix was this: https://github.com/GMOD/Apollo/pull/2007#issuecomment-456572372 

However, the due to a JBrowse bug https://github.com/GMOD/jbrowse/issues/897  . . however, I can only seem to create an error with the line @abretaud  alluded to.  Will comment that out.

**Closed** 2019-02-18 23:11 UTC

**Comment by nathandunn** [comment] 2019-02-19 00:08
The problem is that we need to have `plugins` defined in trackList.json:
```
 "plugins" : [ 
    "HideTrackLabels", 
     { 
         "location" : "https://cdn.rawgit.com/TAMU-CPT/blastview/97572a21b7f011c2b4d9a0b5af40e292d694cbef/", 
         "name" : "BlastView" 
      } 
   ],
``` 

So, without 'stub' and the plugins defined in trackList.json we get this:

<img width="719" alt="screen shot 2019-02-18 at 4 04 04 pm" src="https://user-images.githubusercontent.com/751274/52981797-e022d180-3396-11e9-9670-bb3fb2253ef8.png">

because the plugin is not included properly.

**Comment by abretaud** [comment] 2019-02-19 09:38
Thanks @nathandunn the fix works for me!
