### ISSUE TITLE
Automatic logout warning needed.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#519] opened 2015-08-05 01:29 UTC
We must warn the users that they have been logged out of a session. Currently, Apollo simply stops working without warning, and regardless of how many operations, the requests simply hang. It is only evident the user is "logged out" after refreshing.

**Comment by nathandunn** [comment] 2015-08-05 01:30
Dupe of #493.

**Closed by nathandunn** 2015-08-05 01:30 UTC
Labels: enhancement

**Comment by monicacecilia** [comment] 2015-08-05 01:33
10-4.
