### ISSUE TITLE
add BLAT to Tools panel to fix HTML issues and allow more interoperability with other features

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#585] opened 2015-10-08 23:52 UTC
**Summary**: in certain situations, when the wind blows from the East, BLAT results are not being parsed correctly. 
### Bug one:

One error I have seen is that the display does not wrap the lines correctly, so the first field of the second line of results ends up being tagged to the end of the first line. When this happens, users are still able to hover over any of the fields of results from a line and it will highlight what would have been the complete line of results, and allow users to navigate to those coordinates, - even though the table is not displayed correctly:
- Sometimes this happens on Firefox.
- Sometimes it happens on a Mac on Firefox.
- Sometimes it happens when running Firefox on Linux, on a Mac or otherwise. 

Of course, I was not able to reproduce any of it on a Linux machine today, but the issues with rendering certain features on versions 39 and 40 of firefox are widely known and talked about on the interwebs. It could have been a version issue. - I guess we need to always be sure to tell people to use the latest version of the browser and cross our fingers, for now.

But fear not, I did encounter other issues.
### Bug two:

What we actually have on the results display for Blat is not a table but a collection of divs, which provide no semantic meaning - thus creating difficulties for browsers to read what to display and how -, and the fact that they are being displayed as a "table" at all constitutes a small miracle. So when you squeeze the window as small as possible, things get crowded and the results wrap underneath its own line -- expected, but looks funny -. 

![screen shot 2015-10-08 at 3 56 28 pm](https://cloud.githubusercontent.com/assets/1714621/10382600/73184eb0-6dda-11e5-87b9-d4d2f552e30d.png)
### Proposed solutions:
- The long-term solution for all of this must be creating a new display to conduct Blat searches and offer these results, along with the ability to navigate to each of the results on the table. New from scrap, no hacking of this silly display. 
- In the mean time, at the very least we should dive into this code to turn those divs into an actual table; that would be a good start. 
- We should also add something on the way of "instructions" to let people know that: 
  - the sequence must not include the definition line
  - no spaces are allowed at the beginning or at the end of the sequence
  - they have entered a nucleotide sequence when trying to run a protein search, and vice versa (yes, that again).

**Comment by nathandunn** [comment] 2015-10-09 16:00
- [ ] the sequence must not include the definition line  // I think we should just filter it out
- [ ] no spaces are allowed at the beginning or at the end of the sequence // again I think the input should just do a "trim" on the input
- [ ] they have entered a nucleotide sequence when trying to run a protein search, and vice versa (yes, that again) ..  I think that this is being block by #344 . . these need to be better-defined.

**Comment by nathandunn** [comment] 2015-10-09 16:01
A lot of this is due to jbrowse in an iframe . . . rendering as div's should be fine if we have the correct backing CSS classes

**Comment by monicacecilia** [comment] 2015-10-09 16:14
And that's also a problem right now, the current CSS classes are likely
what's conflicting with browsers.

Let's have a table, please. Pretty please. Very pretty please.

**Comment by nathandunn** [comment] 2015-10-09 16:18
I'll take a look.  A table is not necessarily a better solution, but I think I understand what you are saying (possibly . .  need to start up windows and double-check).

**Comment by nathandunn** [comment] 2015-10-11 02:44
Using bootstrap + div would work . . . basically it doesn't assign row values for divs (!!).   With more people on more devices this is A) an easy fix and B) a more necessary one.   That, or put bootstrap into this (if available), which will have the same effect.

**Comment by nathandunn** [comment] 2015-10-12 21:42
Soo . . @monicacecilia   . . I would propose putting a "Tools" tab in Apollo.  

I was hoping this was just a simple HTML fix.   @GreggHelt2  implemented it correctly in dojo in the way I would have if I had been forced to use dojo.    The "workarounds" / other ways to do this are to use a dojo [TableContainer](https://dojotoolkit.org/reference-guide/1.10/dojox/layout/TableContainer.html) or to programmatically construct a [DataGrid](https://dojotoolkit.org/reference-guide/1.8/dojox/grid/example_Programmatically_creating_a_DataGrid.html).   I'm not convinced that either of these would not suffer the same exact fate . . and both would take a significant amount of time to code. 

Putting it on a separate tools panel will:

A) allow us to more easily to integrate stuff back: https://github.com/GMOD/Apollo/issues/475 (+ more web services)
B) more easily add some of our other services.  

Tools panel can be HTML configured, as well, similar to reports.

**Comment by nathandunn** [comment] 2015-10-12 23:02
I think that doing it this way also gets us to . . we can do analysis in a tab instead of a popup so that it is persistent.

**Comment by monicacecilia** [comment] 2015-10-12 23:09
:+1: Let's try a "Tools" tab!

**Comment by nathandunn** [comment] 2015-10-13 03:05
Its 2.0.2 okay for this?

**Comment by monicacecilia** [comment] 2015-10-13 04:38
Yep.

**Comment by monicacecilia** [comment] 2015-11-13 21:04
... just adding this here because I seriously dislike coming across this darn table error. **Every time** I'm teaching, someone gets this beauty.
![screenshot_apollo_div](https://cloud.githubusercontent.com/assets/1714621/11157543/0d91f200-8a20-11e5-87ea-ec0ef77994ce.png)

**Comment by cmdcolin** [comment] 2015-11-13 21:20
I'm trying to test this out but haven't been able to reproduce. The screenshot confirms that it exists though

I am testing using icebox, under osx, ubuntu, diff browsers, protein/nucl, search all genomic sequences on/off etc. Still haven't gotten it. 

Any tips?

**Comment by nathandunn** [comment] 2015-11-13 21:26
Its VERY specific to IE & Firefox (I think) on Windows.    Chrome on Windows does not do this. 

Try these to reproduce quickly (I use VirtualBox . . but I’m sure any are fine). 

https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/ <https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/>

Either way . . . I don’t think that there is a “quick” fix for this as its hand-coded divs (as opposed to included).   Eventually we want to move this to a panel and out of JBrowse and into the side-bar so we can do other linking without dojo.   

Let’s leave this for when we start on 2.0.2.  

Nathan

**Comment by monicacecilia** [comment] 2015-11-13 21:26
@cmdcolin maybe try using MS Windows 10? That's what they were using.
Thanks for looking into this!

**Comment by monicacecilia** [comment] 2015-11-13 21:27
@nathandunn correct - that's why this is labeled for milestone 2.0.2

**Comment by cmdcolin** [comment] 2015-11-13 21:44
Had a coworker lend me a windows browser and could reproduce.   Have a quick fix comin through...

**Comment by nathandunn** [comment] 2015-11-16 17:32
Pull request doesn't quite fix it in IE 8 / Win 11 (testing in VirtualBox).   This needs to go into a tools panel for a number of reasons.  

<img width="978" alt="screen shot 2015-11-16 at 9 27 26 am" src="https://cloud.githubusercontent.com/assets/751274/11189448/fa98c332-8c44-11e5-872f-caabaaefc12d.png">

**Closed** 2019-10-18 03:37 UTC
Labels: Important, WA1Bug, bug
