### ISSUE TITLE
Script add_transcripts_from_gff3_to_annotations.pl doesn't work for features having Dbxref

### ISSUE THREAD

**Issue by Juke34** [GMOD/Apollo#884] opened 2016-02-16 12:18 UTC
I have an annotation of several thousand genes, and most of them have the Dbxref attribute. Loading this annotation as a track works perfectly well but when I try to load it as user-created Annotations with the script add_transcripts_from_gff3_to_annotations.pl, it works only for mRNAs that don't have any Dbxref attribute. Those having a Dbxref attribute give the following error:
error: 500 Internal Server Error
Processing individual features for failed chunks

As result they are not loaded in the user-created Annotations track.
By the way, I tried using the last webapollo  2.0.2-RC2 version from today.

**Comment by cmdcolin** [comment] 2016-02-16 15:57
I think that I can confirm this bug. I can get an error when a feature with a Dbxref is added at gene level

```
| Error 2016-02-16 09:56:27,524 [http-bio-8080-exec-11] ERROR hibernate.AssertionFailure  - HHH000099: an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: null id in org.bbop.apollo.DBXref entry (don't flush the Session after an exception occurs)
| Error 2016-02-16 09:56:27,561 [http-bio-8080-exec-11] ERROR errors.GrailsExceptionResolver  - AssertionFailure occurred when processing request: [POST] /apollo/annotationEditor/addFeature
null id in org.bbop.apollo.DBXref entry (don't flush the Session after an exception occurs). Stacktrace follows:
Message: null id in org.bbop.apollo.DBXref entry (don't flush the Session after an exception occurs)
    Line | Method
->>  102 | doCall                  in org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     39 | $tt__generateUniqueName in org.bbop.apollo.NameService
|   1699 | $tt__addFeature . . . . in org.bbop.apollo.RequestHandlingService
|    163 | addFeature              in org.bbop.apollo.AnnotationEditorController
|    198 | doFilter . . . . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter                in grails.plugin.cache.web.filter.AbstractFilter
|    449 | executeChain . . . . .  in org.apache.shiro.web.servlet.AbstractShiroFilter
|    365 | call                    in org.apache.shiro.web.servlet.AbstractShiroFilter$1
|     90 | doCall . . . . . . . .  in org.apache.shiro.subject.support.SubjectCallable
|     83 | call                    in     ''
|    383 | execute . . . . . . . . in org.apache.shiro.subject.support.DelegatingSubject
|    362 | doFilterInternal        in org.apache.shiro.web.servlet.AbstractShiroFilter
|    125 | doFilter . . . . . . .  in org.apache.shiro.web.servlet.OncePerRequestFilter
|   1145 | runWorker               in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run                     in java.lang.Thread
```

**Comment by cmdcolin** [comment] 2016-02-16 16:02
Also happens in 2.0.1 so not a new bug per se.

**Comment by cmdcolin** [comment] 2016-02-16 16:24
As far as why it happens (on line with Gene.countByName), it is probably because this triggers session flush (similar to what I saw in #864)

**Comment by nathandunn** [comment] 2016-02-16 17:00
The problem is that findOrSave method for DBXref . . . I'll fix it momentarily.

**Comment by nathandunn** [comment] 2016-02-16 17:12
@Juke34   this should be fixed and in the master.  Please re-open if not.

**Closed by nathandunn** 2016-02-16 17:12 UTC
Labels: bug, Important, Ready

**Comment by Juke34** [comment] 2016-02-17 13:07
Yes it works perfectly fine now. Thank you so much.
