### ISSUE TITLE
Logging in loses place

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1363] opened 2016-12-02 19:35 UTC
I think there is a regression bug in RC1.  When logging in I go to a different location (scaffold) from where I was when in not-logged-in mode. In my example, I went from scaffold66 to scaffold5765 after logging in.

Since location information is now stored in the clientToken, I'm not sure how useful the URLs would be, but I can pull records from the preference table if that would be helpful.

Organism is the same.
Version info:
```text

Apollo Genome Annotator

    Version: 2.0.5-RC1
    Grails version: 2.5.5
    Groovy version: 2.4.4
    JVM version: 1.8.0_112

```

**Comment by childers** [comment] 2016-12-02 19:38
Forgot to add, track and features display properly once manually navigating to the right scaffold.

**Comment by nathandunn** [comment] 2016-12-02 19:41
Related to #1007

**Comment by nathandunn** [comment] 2016-12-02 22:01
Closing in favor of #1007.  The issue is that its not saving user preferences often enough.

**Closed by nathandunn** 2016-12-02 22:01 UTC
Labels: bug, in progress
