### ISSUE TITLE
Failure to load tracks when switching organisms with identical Sequence IDs

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1391] opened 2016-12-19 17:51 UTC
I think this is a regression, as this behavior did not seem to be in 2.0.4:

Working on this with @mpoelchau:

We have cleared browser caches, the preferences table and can replicate. The scaffold names are identical between orgA and orgB, and some tracks are named the same (augustus_masked) while others are named uniquely to that organism (orgA_OGS, orgA_maker).  

1. Started with one organism (orgA)
2. Created some annotations on scaffold1
3. Start working on orgB; switched organisms via annotator panel (the one on the right, not the jbrowse option on the left)
4. Switched me to scaffold5192. So far so good. 
5. Manually refresh in order for orgB tracks to display
6. Select augustus_masked (track shared between organisms), Official gene set, orgB models.
7. Select scaffold1 in the jbrowse viewer. 
6. Moves me to scaffold1. OrgA annotations show up. augustus_masked track displays data; official gene set and orgB specific tracks do not display.
 

**Example images showing the above workflow:**
* Switched from orgA to orgB
![just-switched-to-orgb-from-orga](https://cloud.githubusercontent.com/assets/421248/21322626/0491329c-c5e8-11e6-8019-4c43c65b926b.png)

* track showing orgA augustus is loaded on orgB
![orgb-augustus_problem](https://cloud.githubusercontent.com/assets/421248/21322624/048f95a4-c5e8-11e6-8b78-94d24dcd17db.png)

* Seeing orgA annotations while on orgB 
![orga-orgb_problem](https://cloud.githubusercontent.com/assets/421248/21322625/0490f8ae-c5e8-11e6-89cd-6521ee509503.png)

**Example 2: error with tracks loading incorrectly when switching organisms**
* Switched organisms orgC to orgD, but the tracks are still showing for orgC 
<img width="1439" alt="apollo2 0 5-track-error-a" src="https://cloud.githubusercontent.com/assets/421248/21322988/81c5ad32-c5e9-11e6-9b91-f0990eaa23ef.png">

* Reload, and no tracks found error!
<img width="1436" alt="apollo2 0 5-track-error-b" src="https://cloud.githubusercontent.com/assets/421248/21322992/85468ef4-c5e9-11e6-8121-7aadc6c19adc.png">

* Native track selector enabled to show tracks are present
<img width="1436" alt="apollo2 0 5-track-error-c" src="https://cloud.githubusercontent.com/assets/421248/21323004/91d4d522-c5e9-11e6-81fd-7641000fd76f.png">

**Comment by nathandunn** [comment] 2016-12-19 17:57
@childers  @mpoelchau 
What happens when you click on the Annotations Panel and back onto the Tracks panel? 
- with the native track selector selected
- without the native track selector selected

The tracks panel is populated from the JBrowse screen.  If there is an error in timing it might potentially not be there, so clicking back and forth *SHOULD* bring it up (though unsure if the native browser will interfere with that).  

It could be more robust using a JBrowse milestone to trigger population.

**Comment by mpoelchau** [comment] 2016-12-19 20:01
@nathandunn : 

I think this may be a problem with a delay either in communicating information from the Apollo panel to Jbrowse, or perhaps in loading the track data. If you do step 4 of the workflow I list below quickly (clicking on a track's radio button immediately after the Tracks panel is loaded), you get a really confusing mix of organisms and tracks (see image in step 6 below). However, if you wait for ~10 seconds before clicking on the radio button, everything displays fine. 

1. Start out with organism Latrodectus hesperus; select 1 track
![screen shot 2016-12-19 at 12 25 37 pm 2](https://cloud.githubusercontent.com/assets/5487172/21326172/b8c50286-c5e6-11e6-82d9-02c2e7207343.png)

2. Switch to organism Loxosceles reclusa using Apollo panel
3. No tracks are initially displayed (see image 1). I don't get Chris' 'No tracks' error, but the tracks won't load even if you wait for a long time.
![screen shot 2016-12-19 at 12 25 49 pm 2](https://cloud.githubusercontent.com/assets/5487172/21326185/c5d5136c-c5e6-11e6-945e-e2cba0fa6331.png)

4. Tracks panel is populated after clicking on Annotations Panel and then Tracks Panel. However, if you click on a track, JBrowse won't show the content (however, it WILL show if you wait a bit longer before you select the track - and the errors listed below won't occur) 
![screen shot 2016-12-19 at 12 25 55 pm 2](https://cloud.githubusercontent.com/assets/5487172/21326209/e13508d8-c5e6-11e6-8788-cb19158c3ea4.png)

5. Click on 'Show JBrowse Track Selector' (side note - this radio button is REALLY hard to find if you don't know what you're looking for)

6. JBrowse track selector and organism selector now show information from Latrodectus hesperus, NOT Loxosceles reclusa. Also, the Jbrowse organism selector shows Latrodectus hesperus, not Loxosceles reclusa. It looks like there's a disconnect between the organism that JBrowse thinks it should display vs. the one Apollo thinks it should display.
![screen shot 2016-12-19 at 12 26 50 pm 2](https://cloud.githubusercontent.com/assets/5487172/21326249/04d63604-c5e7-11e6-81b5-10b55b67f472.png)


Assuming that the problem is some sort of a delay - It would be good if there was a way to prevent a user from clicking on a track before the program is completely ready to go.

**Comment by nathandunn** [comment] 2016-12-20 00:12
@mpoelchau  / @childers   alright, diving in and crossing fingers.  Thanks for the attention to detail.

**Comment by nathandunn** [comment] 2016-12-20 00:21
@mpoelchau / @childers  Ughh . . . okay, I know what's going on.  Its just loading whats in the store, not the other organism.   Whatever you get off the Annotator Panel is correct.

**Comment by nathandunn** [comment] 2016-12-20 00:50
Its a bit weirder than that.  The cache will randomly pick which one it wants to use, so I think that there are multiple sets of data and it will switch back and forth between the two.  The track selection (or lack thereof) is just an artifact of the cache not being cleaned out for those tracks.    

We could definitely get rid of the drop-down, but not the lookup, but it blows me away that it has two versions of the cached to choose from.

**Comment by nathandunn** [comment] 2016-12-20 00:51
I'm almost positive that this has always been like this, but I can recheck with 2.0.4 to make sure.

**Comment by nathandunn** [comment] 2016-12-20 00:54
This is what we use for training instances, so I'll give it a quick test and see.

**Comment by nathandunn** [comment] 2016-12-20 01:03
Confirmed that this a regression.  Not able to reproduce this in 2.0.4 off one of the training instances.

**Comment by nathandunn** [comment] 2016-12-20 01:31
I think I'm at stage 4 of 5 in the states of acceptance of a bug occurring.    Definitely through bargaining.

**Comment by nathandunn** [comment] 2016-12-20 01:44
(notes to self) In AnnotTrack.js , this is what is called:

                    browser.subscribe("/jbrowse/v1/n/navigate", dojo.hitch(this, function (currRegion) {
                        window.parent.handleNavigationEvent(JSON.stringify(currRegion));
                    }));

this is resolved in MainPanel.java under handleNavigationEvent:

      if (handlingNavEvent) return;

        handlingNavEvent = true;
        JSONObject navEvent = JSONParser.parseLenient(payload).isObject();

        final Integer start = (int) navEvent.get("start").isNumber().doubleValue();
        final Integer end = (int) navEvent.get("end").isNumber().doubleValue();
        String sequenceNameString = navEvent.get("ref").isString().stringValue();

        if (!sequenceNameString.equals(currentSequence.getName())) {
            setCurrentSequence(sequenceNameString, start, end, false, true);
            Scheduler.get().scheduleFixedPeriod(new Scheduler.RepeatingCommand() {
                @Override
                public boolean execute() {
                    return handlingNavEvent;
                }
            }, 200);

        } else {
            sendCurrentSequenceLocation(sequenceNameString, start, end);
        }

**Comment by nathandunn** [comment] 2016-12-20 01:49
(more notes to self)

All of these methods work flawlessly.  SuggestBox drop-down:

                    setCurrentSequence(sequenceSuggestBox.getText().trim(), null, null, true, false);

the organism calls the server:

                    MainPanel.getInstance().setAppState(AppInfoConverter.convertFromJson(returnValue));

Double-clicking does it the same way:

      OrganismRestService.switchSequenceById(sequenceInfo.getId().toString());

**Closed** 2016-12-20 23:13 UTC
Labels: bug, Important, in progress

**Comment by nathandunn** [comment] 2016-12-21 03:01
I'm not sure if this fixed the track issue, but its kind of the same one, so probably.
