### ISSUE TITLE
Undo/History for changes other than structural

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1060] opened 2016-05-25 22:54 UTC
Wishlist item :)

The feature history currently only includes structural changes. We noted over the course of our course that it would be incredibly useful if that feature history also included things like users adding / removing / changing annotations on the feature.

That way we can keep an accurate log of who added a feature name, and allow undoing various changes. 

We had one student who ran a tool which renamed all of their genes. Had this been a logged change in the feature history, the student could have gone through each feature and reverted the names appropriately.

**Comment by nathandunn** [comment] 2016-05-25 23:08
I think that this is a dupe of this #541.   I'll post your comment there.   Definitely need to think about this.  Maybe we just log it different.

**Closed by nathandunn** 2016-05-25 23:08 UTC

**Comment by erasche** [comment] 2016-05-25 23:12
@nathandunn sounds good. Thanks.
