### ISSUE TITLE
Logging/Audit trail for annotation edits.

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#208] opened 2015-03-30 21:02 UTC
Per email comments, we'd be interested in increased logging on the Changes page. @monicacecilia mentioned that there were plans for this, though what information should be visible was less well defined. 

Here's a non-exhaustive, very wishlist-y list of features that would be nice in increased logging:

- basically we want an audit trail, where every notation corresponds to a diffable change in the "user annotation" gff3 view (not that we actually need diffs, that would be crazy)
- It'd be nice to know:
  - who changed,
  - what and,
  - when.
  - from what/to what.
- if those log entries could be generated with permalinks of some sort to the feature that was changed so that the log viewer could go investigate the possible evidence for that change being made

e.g.

Sequence |User | Date | Change
--- | --- | --- | ---
chr1 | jane | 2014-12-23T00:00 | Added [mRNA](example.com/apollo/jbrowse/?loc=chr1&feature=3) (where mRNA is linked to the one that was created)
chr1 | bob | 2014-12-23T01:00 | Removed mRNA  
chr1 | jane | 2014-12-23T02:00 | Added [dbxref](example.com/apollo/jbrowse/?loc=chr1&feature=3#dbxref) InterPro:IPR000012
chr1 | jane | 2014-12-23T02:00 | Changed [note](example.com/apollo/jbrowse/?loc=chr1&feature=3#note) from "DNA Topoisomerase" to "DNA Topoisomerase II"

**Comment by nathandunn** [comment] 2015-03-30 21:15
@erasche   Thanks.  I put this in 2.1  . . . however, knowing who the annotation owners will come in 2.0.

**Comment by nathandunn** [comment] 2015-04-29 17:37
As a first-pass when can make sure to turn on Audit Logging. . . We can add reports after that.

**Comment by erasche** [comment] 2015-04-29 17:39
@nathandunn sounds good!

**Comment by nathandunn** [comment] 2015-05-07 18:11
This should be active in the 2.0.0 release (when it is released).  In 2.0.1 we (or anyone else) should be able to create pages based on the recorded logs as GSP pages.  I'll try to stub an AuditController and at least one GSP page for this.

**Comment by nathandunn** [comment] 2015-08-07 16:04
@deepakunni3   This is related to #488 .  Feel free to merge the two.

**Comment by erasche** [comment] 2015-08-07 18:09
@nathandunn excellent! thanks

**Comment by nathandunn** [comment] 2016-04-07 22:36
Closing this as a duplicate of #488 (changes + feature event history) . . . if we still need this level of logging, we can re-open it.

**Closed by nathandunn** 2016-04-07 22:36 UTC
Labels: enhancement
