### ISSUE TITLE
503 error: context.GrailsContextLoaderListener  - Error initializing the application: null

### ISSUE THREAD

**Issue by holmrenser** [GMOD/Apollo#465] opened 2015-07-03 12:41 UTC
I recently pulled some updates and now the entire webapollo does not work anymore. Webbrowser shows a 503: Problem accessing /apollo/. Reason: Service Unavailable.

Jetty log:

        Shiro Configured
        2015-07-03 14:37:39,675 [main] ERROR context.GrailsContextLoaderListener  - Error initializing the application: null
        java.lang.NullPointerException
                at grails.plugin.cache.ehcache.GrailsEhCacheManagerFactoryBean$ReloadableCacheManager.rebuild(GrailsEhCacheManagerFactoryBean.java:171)
                at grails.plugin.cache.ehcache.EhcacheConfigLoader.reload(EhcacheConfigLoader.groovy:63)
                at grails.plugin.cache.ConfigLoader.reload(ConfigLoader.groovy:42)
                at CacheGrailsPlugin.reloadCaches(CacheGrailsPlugin.groovy:202)
                at CacheGrailsPlugin$_closure3.doCall(CacheGrailsPlugin.groovy:158)
                at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
                at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
                at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
                at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
                at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
                at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
                at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
                at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
                at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
                at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
                at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
                at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:455)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
                at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)
                at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)
                at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)
                at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560)
                at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
                at org.eclipse.jetty.server.Server.start(Server.java:387)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
                at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
                at org.eclipse.jetty.server.Server.doStart(Server.java:354)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255)
                at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
                at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)
                at org.eclipse.jetty.start.Main.start(Main.java:817)
                at org.eclipse.jetty.start.Main.main(Main.java:112)
        2015-07-03 14:37:39,681 [main] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: null
        java.lang.NullPointerException
                at grails.plugin.cache.ehcache.GrailsEhCacheManagerFactoryBean$ReloadableCacheManager.rebuild(GrailsEhCacheManagerFactoryBean.java:171)
                at grails.plugin.cache.ehcache.EhcacheConfigLoader.reload(EhcacheConfigLoader.groovy:63)
                at grails.plugin.cache.ConfigLoader.reload(ConfigLoader.groovy:42)
                at CacheGrailsPlugin.reloadCaches(CacheGrailsPlugin.groovy:202)
                at CacheGrailsPlugin$_closure3.doCall(CacheGrailsPlugin.groovy:158)
                at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
                at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
                at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
                at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
                at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
                at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
                at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
                at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
                at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
                at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
                at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
                at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:455)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
                at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)
                at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)
                at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)
                at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560)
                at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
                at org.eclipse.jetty.server.Server.start(Server.java:387)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
                at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
                at org.eclipse.jetty.server.Server.doStart(Server.java:354)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255)
                at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
                at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)
                at org.eclipse.jetty.start.Main.start(Main.java:817)
                at org.eclipse.jetty.start.Main.main(Main.java:112)
        2015-07-03 14:37:39.683:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@6f3f154b{/apollo,file:/tmp/jetty-0.0.0.0-8080-apollo.war-_apollo-any-966733845034195641.dir/webapp/,STARTING}{/apollo.war}
        org.springframework.beans.factory.access.BootstrapException: Error executing bootstraps; nested exception is java.lang.NullPointerException
                at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:126)
                at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
                at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
                at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
                at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
                at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
                at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
                at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
                at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
                at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
                at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
                at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
                at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
                at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:455)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
                at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)
                at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)
                at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)
                at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560)
                at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
                at org.eclipse.jetty.server.Server.start(Server.java:387)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
                at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
                at org.eclipse.jetty.server.Server.doStart(Server.java:354)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)
                at org.eclipse.jetty.start.Main.start(Main.java:817)
                at org.eclipse.jetty.start.Main.main(Main.java:112)
        Caused by: 
        java.lang.NullPointerException
                at grails.plugin.cache.ehcache.GrailsEhCacheManagerFactoryBean$ReloadableCacheManager.rebuild(GrailsEhCacheManagerFactoryBean.java:171)
                at grails.plugin.cache.ehcache.EhcacheConfigLoader.reload(EhcacheConfigLoader.groovy:63)
                at grails.plugin.cache.ConfigLoader.reload(ConfigLoader.groovy:42)
                at CacheGrailsPlugin.reloadCaches(CacheGrailsPlugin.groovy:202)
                at CacheGrailsPlugin$_closure3.doCall(CacheGrailsPlugin.groovy:158)
                at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
                at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
                at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
                at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
                at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
                at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
                at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
                at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
                at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
                at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
                at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
                at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:455)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
                at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)
                at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)
                at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)
                at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560)
                at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
                at org.eclipse.jetty.server.Server.start(Server.java:387)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
                at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
                at org.eclipse.jetty.server.Server.doStart(Server.java:354)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255)
                at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
                at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)
                at org.eclipse.jetty.start.Main.start(Main.java:817)
                at org.eclipse.jetty.start.Main.main(Main.java:112)

**Comment by nathandunn** [comment] 2015-07-03 16:36
There are a few possibilities.   My guess is that it is trying to write out cache to a directory its not allowed to.  Very surprised that its doing this on startup (or at all).   Some suggestions (I've not been able to reproduce it):

0) Make sure you did a clean install, removing the "<apollo>" directory in your jetty webapps directory. 
1) Make sure you have at least 1 GB of memory (Xmx) for your server. 
2) Make sure that the write permissions in the jetty directory are all the same
3) if all else fails, disable the cache (in ```apollo-config.groovy```), which will turn off this feature:  

```grails.cache.enabled=false```
```cache.config.cache.enabled = false```

  Let us know how it goes.

**Comment by cmdcolin** [comment] 2015-07-03 17:20
Just curious have you done a 'git pull' recently?


I had this error at one point but it seems to have gone away

**Comment by holmrenser** [comment] 2015-07-03 20:01
Latest pull was this morning, I'll try Nathan's suggestions first thing tomorrow

**Comment by nathandunn** [comment] 2015-07-07 16:43
@holmrenser   Any luck?

**Comment by holmrenser** [comment] 2015-07-08 11:13
0), 1) & 2) are check.
Trying 3) now, but having some problems:
	0    [main] WARN  org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper  - Unable to load specified config location file:./apollo-config.groovy : File does not exist.
	423  [main] WARN  org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper  - Unable to load specified config location classpath:apollo-config.properties : File does not exist.

I have seen this before but forgot the fix. I am assuming this means any additional thins I specify in apollo-config.groovy don't get used?

**Comment by nathandunn** [comment] 2015-07-08 17:07
@holmrenser  If you want to run anything other than the H2 embedded database that it comes with you'll need to copy one of the sample-XXX-apollo-config.groovy to apollo-config.groovy.  If you are going to run off of Jetty or Tomcat you pretty much need to do this (even if you continue to use h2) because the default h2 location typically can't be written to by the Jetty / Tomcat user.   More instructions are here:

https://webapollo.readthedocs.org/en/latest/Apollo2Build/

Let me know if you have any questions.

**Comment by holmrenser** [comment] 2015-07-09 06:41
I know, that is what I am doing, I am using postgresql.

**Comment by nathandunn** [comment] 2015-07-09 15:42
from this line:

    2015-07-03 14:37:39.683:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@6f3f154b{/apollo,file:/tmp/jetty-0.0.0.0-8080-apollo.war-_apollo-any-966733845034195641.dir/webapp/,STARTING}{/apollo.war}

It looks like the tomcat user may not have write permissions on the "/tmp" directory?  

That being said, nothing is wrong with removing the disk cache (or the cache altogether).   I'll try to find the appropriate over-ride settings and respond with those.

**Comment by nathandunn** [comment] 2015-07-09 21:42
@holmrenser   I updated our trouble-shooting doc to reflect this problem.  Basically you can turn off the cache, remove writing it to disk, or specify the directory:

https://github.com/GMOD/Apollo/blob/master/docs/Troubleshooting.md#cache-error

I tested these and they seemed to work.  Let me know if you want to do anything more specific or have any other questions.

**Comment by holmrenser** [comment] 2015-07-10 12:08
I tried the suggested fix, and that didn't work. 
For the record, I was using jetty. I recently noticed this error:

	0    [main] WARN  org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper  - Unable to load specified config location file:./apollo-config.groovy : File does not exist.
	419  [main] WARN  org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper  - Unable to load specified config location classpath:apollo-config.properties : File does not exist.

Not sure if this is related though.

After switching to tomcat (at first I was not able to use tomcat) the problem is fixed, also without disabling the ehcache.
I get the feeling I am doing something wrong with jetty...
Thanks for the help anyway!

**Comment by nathandunn** [comment] 2015-07-10 14:47
Weird.  At the top of the Config file it is supposed to load the apollo-groovy file, by telling it where to look.  The "apollo deploy" script is supposed to put it in the class path.   Those warnings don’t surprise me since apollo-config.groovy is compiled into the class path. 

Glad that tomcat worked.  When we tested with Jetty we didn’t have any problems, but I would agree that there is something screwy about your jetty environment.  

Shall I close it?

Nathan

**Comment by monicacecilia** [comment] 2015-08-12 21:42
I'm going to assume that this solved @holmrenser 's problems and that Tomcat cleared things. - if additional issues arise using Jetty, then we will have to open a different issue. 
closing.

**Closed by monicacecilia** 2015-08-12 21:42 UTC
Labels: discussion, Ready
