### ISSUE TITLE
DB Multiple connection errors? Row was updated or deleted by another transaction

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1486] opened 2017-02-09 21:44 UTC
```
2/9/2017 9:43:19 PM2017-02-09 21:43:19,438 [http-apr-8080-exec-28] ERROR errors.GrailsExceptionResolver  - StaleObjectStateException occurred when processing request: [GET] /apollo/376276834172582201465765055/jbrowse/data/tracks.conf
2/9/2017 9:43:19 PMRow was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.UserOrganismPreference#275565]. Stacktrace follows:
2/9/2017 9:43:19 PMorg.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.UserOrganismPreference#275565]
2/9/2017 9:43:19 PM	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismPreference(PreferenceService.groovy:183)
2/9/2017 9:43:19 PM	at org.bbop.apollo.PreferenceService.$tt__getOrganismFromPreferences(PreferenceService.groovy:252)
2/9/2017 9:43:19 PM	at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismForCurrentUser(PreferenceService.groovy:16)
2/9/2017 9:43:19 PM	at org.bbop.apollo.JbrowseController.getJBrowseDirectoryForSession(JbrowseController.groovy:154)
2/9/2017 9:43:19 PM	at org.bbop.apollo.JbrowseController.data(JbrowseController.groovy:197)
2/9/2017 9:43:19 PM	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
2/9/2017 9:43:19 PM	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
2/9/2017 9:43:19 PM	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
2/9/2017 9:43:19 PM	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
2/9/2017 9:43:19 PM	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
2/9/2017 9:43:19 PM	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
2/9/2017 9:43:19 PM	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
2/9/2017 9:43:19 PM	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
2/9/2017 9:43:19 PM	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
2/9/2017 9:43:19 PM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2/9/2017 9:43:19 PM	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2/9/2017 9:43:19 PM	at java.lang.Thread.run(Thread.java:745)
2/9/2017 9:43:19 PM2017-02-09 21:43:19,800 [http-apr-8080-exec-16] WARN  apollo.JbrowseController  - File not found: /jbrowse/sample_data/json/volvox/successfully_run
2/9/2017 9:43:22 PM2017-02-09 21:43:22,700 [http-apr-8080-exec-26] ERROR apollo.SequenceController  - Object of class [org.bbop.apollo.UserOrganismPreference] with identifier [275571]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.UserOrganismPreference#275571
```

Mostly leaving this here for others who are googling. No idea what is causing this.

**Comment by nathandunn** [comment] 2017-02-09 21:52
If you delete from your preference directory and reload what do you see?

**Comment by erasche** [comment] 2017-02-09 21:53
This is preventing access to a couple organisms. Reloading sometimes fixes it, maybe it's hitting another thread. Race condition?

**Comment by erasche** [comment] 2017-02-09 21:54
I wiped out the preference table and the first reload failed, the second reload loaded. Subsequent reloads seem to be workign?

**Comment by nathandunn** [comment] 2017-02-09 21:59
So, have you been doing this and the issue keeps popping up?

**Comment by nathandunn** [comment] 2017-02-09 22:02
By "doing this" I mean "cleaning out the preference table".   My hope is that its just an upgrade issue.  If not, let me know.  The request that is failing is this and "client_token" is unique to each browser:

                "update UserOrganismPreference  pref set pref.currentOrganism = false " +
                        "where pref.id != :prefId and pref.user = :user and pref.clientToken = :clientToken",

**Comment by erasche** [comment] 2017-02-09 22:10
Yes, cleaning out pref table, not `truncate`, just deleting the ones pertaining to a particular user. I was a bit scared of truncating the entire pref table.

Agreed, hope it's just an upgrade issue, but I'm a bit worried about the pref table in general--every single API request was generating a new entry.

Sorry for noise / an issue that's nigh impossible to debug remotely.

**Comment by nathandunn** [comment] 2017-02-09 22:22
I should have fixed the API request issue.  It shouldn't try to generate preference entries now if you don't pass in a client_token, but DO pass in an organism.   Let me know if this is not the case. 

The idea is that it stores one preference for each organism, sequence, user, and browser (client_token) combination.  This should get cleaned out if the entries are stale after a month or so.

**Comment by erasche** [comment] 2017-04-25 19:07
From private chat, these are all the (look like unique) exceptions that I get.

with genes:

```
2017-04-20 16:29:34,440 [clientInboundChannel-4] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
        at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1144)
        at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1143)
        at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1139)
        at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
        at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is mixed; nested exception is org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [org.bbop.apollo.Gene] with identifier [354856]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.Gene#354856]
        ... 8 more
Caused by: org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [org.bbop.apollo.Gene] with identifier [354856]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.Gene#354856]
        ... 8 more
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.Gene#354856]
        ... 8 more

```

and with our custom terminator type

```
2017-04-20 16:24:36,347 [clientInboundChannel-3] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
        at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1144)
        at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1143)
        at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1139)
        at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
        at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [org.bbop.apollo.Terminator] with identifier [518260]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.Terminator#518260]
        at org.bbop.apollo.RequestHandlingService.setName(RequestHandlingService.groovy:489)
        ... 8 more
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.Terminator#518260]
        ... 9 more

```

row updated

```
2017-04-17 20:14:01,300 [http-nio-8080-exec-8] ERROR apollo.SequenceController  - Object of class [org.bbop.apollo.UserOrganismPreference] with identifier [506828]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.UserOrganismPreference#506828]
```

The preferences one happens a LOT. we also see this:

```
2017-04-25 17:15:19,358 [http-nio-8080-exec-31] WARN  apollo.PreferenceService  - Multiple preferences found: 15
```

I've seen that one some 2600 times in the last week alone (~20 people working on annotation). If you're curious what the distribution of # of duplicate preferences found are... well you're in for a treat.

```
$ cat out.log | grep 'WARN  apollo.PreferenceService  - Multiple preferences found: \d*' | awk '{print $10}' | sort -n | uniq -c
   2047 2
    265 3
     48 4
    134 5
     18 6
     27 7
     14 8
     10 9
      9 10
      2 11
      2 12
      1 13
      2 14
      1 15
      2 16
      2 17
      1 18
      2 20
      2 24
      1 32
      1 34
      1 57
      1 58
      1 59
      1 60
      1 61
      1 62
      1 63
      1 64
      1 65
      1 66
      1 67
      1 68
      1 69
      1 70
      1 71
      1 72
      1 73
      1 74
      1 75
      1 76
      1 77
      1 78
```

this exciting one

```
2017-04-18 18:40:37,743 [http-nio-8080-exec-2] ERROR spi.SqlExceptionHelper  - ERROR: deadlock detected
  Detail: Process 81332 waits for ShareLock on transaction 287016; blocked by process 81350.
Process 81350 waits for ShareLock on transaction 287015; blocked by process 81332.
  Hint: See server log for query details.
  Where: while updating tuple (30,29) in relation "preference"
2017-04-18 18:40:37,819 [http-nio-8080-exec-2] ERROR errors.GrailsExceptionResolver  - PSQLException occurred when processing request: [POST] /apollo/annotator/setCurrentOrganism/240096
ERROR: deadlock detected
  Detail: Process 81332 waits for ShareLock on transaction 287016; blocked by process 81350.
Process 81350 waits for ShareLock on transaction 287015; blocked by process 81332.
  Hint: See server log for query details.
  Where: while updating tuple (30,29) in relation "preference". Stacktrace follows:
org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 81332 waits for ShareLock on transaction 287016; blocked by process 81350.
Process 81350 waits for ShareLock on transaction 287015; blocked by process 81332.
  Hint: See server log for query details.
  Where: while updating tuple (30,29) in relation "preference"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135)
        at org.bbop.apollo.PreferenceService.setOtherCurrentOrganismsFalse(PreferenceService.groovy:60)
        at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismPreference(PreferenceService.groovy:166)
        at org.bbop.apollo.PreferenceService.$tt__getCurrentOrganismPreference(PreferenceService.groovy:260)
        at org.bbop.apollo.AnnotatorService.$tt__getAppState(AnnotatorService.groovy:46)
        at org.bbop.apollo.AnnotatorController.$tt__setCurrentOrganism(AnnotatorController.groovy:438)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-04-18 18:40:38,397 [http-nio-8080-exec-2] WARN  apollo.PreferenceService  - Multiple preferences found: 3
2017-04-18 18:40:38,399 [http-nio-8080-exec-4] WARN  apollo.PreferenceService  - Multiple preferences found: 3
2017-04-18 18:40:38,756 [http-nio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - StaleObjectStateException occurred when processing request: [GET] /apollo/1443843259362269271263300263/jbrowse/data/tracks.conf
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by erasche** [comment] 2017-04-25 19:08
"All" meaning "all relevant", the others look like temporary hiccups on auth, that sort of thing. irrelevant. Happy to provide full logs if need be, but I know I'm not helping debuging with my crazy complex setup. Fixing these things blind is crazy hard I recognise. I'm still trying to isolate reproducible cases from many of these but it is a slow process

**Comment by nathandunn** [comment] 2017-04-25 20:36
I'll try to take a look at these tomorrow. I think the problem is that we have many threads from many users accessing the preferences table at multiple times.  I should probably just set a failable lock of some type.  Will have to think about it some more.

**Comment by nathandunn** [comment] 2017-04-25 23:29
@erasche  It is in now my list of things to do when not working on projection.  Hopefully I'll be able to work on this later this week or next week when I need a break.  Please fill in additional information if you run into any.  

I'm trying to figure out what the best way to figure this out might be.  In some cases, the preferences can be set asynchronously, or otherwise set in a more succinct manner.    Probably the best thing would be to simulate with a bunch of different users, using several different scaffolds.  

WRT to your Terminator error, one way to fix the stale object preferences is to requery it from the database (depending on how you are accessing it):

    Terminator t = // get somehow
    // other stuff happens
    // do one of these 
    t.refresh()   // re-queries and populates form the database

**Comment by erasche** [comment] 2017-04-26 00:32
Fwiw, I'm not doing anything special at all with terminators, I basically copied + pasted repeat_region and just changed the name. They're being accessed just like any other feature. I'm not sure why they show up disproportionately in the logs.

Thanks for being willing to take a look at this! I appreciate the second set of eyes.

**Comment by nathandunn** [comment] 2017-04-26 04:40
If you can point me to the branch the terminator is on I can take a look.

Also if it makes sense to send me a dockerized dump for the other stuff I can take a look.  My intuition is that it will be hard to reproduce without lots of users, simulated or otherwise, pounding away.  Unless you are getting this problem when the system is quiet as well. 

Nathan

**Comment by erasche** [comment] 2017-04-26 05:18
https://github.com/erasche/apollo/tree/viral-annotation

(I'll try and export everything, but parts of it are a bit intricately linked, I'm not sure how they'll function outside of the specific environment. E.g. remote user proxy is tied right into our galaxy database. I know that service is generating a non-zero number of auth errors under various circumstances, I have to wonder how that's affecting things.)

**Comment by nathandunn** [comment] 2017-04-26 17:00
I looked at the code for Terminator and it all looks good if you wanted it to behave like Repeat_Region.  

If the issue seems related to running in docker my intuition is that there may be database latency issues within docker, but I don't know.  I would see if there is a way to test PostgreSQL inside and outside of Docker for the data you have.

Also, with the number of users you have, I would run with -Xmx2GB for tomcat, especially if working on a large number of organisms + users.  This will help caching and performance.  

All that being said, Apollo should still be reliably handling those conditions.   

Of the errors above, are any of them directly associated with failures on the user-interface (you had said something about inability to scroll)?

**Comment by erasche** [comment] 2017-04-26 17:20
I would be surprised if there were DB latency issues. The DB is running on the same machine as apollo and it's relatively isolated from other services. Docker should have a negligible impact on latency in this case.

As for memory: ![utvalg_045](https://cloud.githubusercontent.com/assets/458683/25447335/55a1063c-2aa4-11e7-8969-226152f30c3e.png)

The only user-facing issues we've really seen is https://github.com/GMOD/Apollo/issues/1543 but I still have not been able to isolate that and debug it. Another only-in-production issue it seems...

**Comment by nathandunn** [comment] 2017-04-26 17:38
Yeah, I probably just need to up the testing on this for heavy load with multiple users.

**Comment by nathandunn** [comment] 2017-04-26 17:40
No idea about #1543 either.    Somehow the data is null.  If you post the GFF3 for that it might help.

**Comment by nathandunn** [comment] 2017-05-18 21:17
@erasche  Is there a way you could see if #1604 fixes this?

**Comment by nathandunn** [comment] 2017-05-24 16:59
@erasche   Can I close this for now and you can see if it is reproduced if you update to master?

**Closed** 2017-05-24 16:59 UTC
Labels: bug

**Comment by erasche** [comment] 2017-05-24 17:11
Hey @nathandunn sorry I missed this, I'll test when I can but I'm not sure when that will be. We've frozen the version of apollo that we've deployed since I'm leaving that position and it will be a while before the replacement can safely upgrade the stack. I can test it locally but I mostly saw those errors in production.
