### ISSUE TITLE
Plus/minus strand filters make bigwig go to zero

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#181] opened 2015-02-26 19:02 UTC
In previous versions strand filters have a side effect of filtering out features with no strand specified. This actually had the weird effect of making bigwig tracks go to zero as well since they are composed of small quantitative features with no strand iirc

This was changed to not do this on 1.0.4-various-fixes

Some screenshot examples before&after applying the "minus strand filter"

![screenshot-icebox lbl gov 2015-02-26 12-26-29](https://cloud.githubusercontent.com/assets/6511937/6399345/62464ffc-bdb7-11e4-9d46-a9550d2f5dbe.png)
![screenshot-icebox lbl gov 2015-02-26 12-26-36](https://cloud.githubusercontent.com/assets/6511937/6399346/62e8d36c-bdb7-11e4-97cd-fd4c3ec7a441.png)

Originally reported here https://trello.com/c/3xJ9IOJA/346-the-plus-minus-strand-filters-make-the-bigwig-tracks-go-to-0

**Comment by monicacecilia** [comment] 2015-03-07 00:14
The bug reported here has been fixed. Thanks!

Note: The behavior when applying both filters (toggle plus strand, toggle minus strand) at once results in bigwig files "displayed at 0" (both XY coverage and heatmap coverage display). This is acceptable and expected, not a bug -- if there are no data on either strand, then no coverage to display.

**Comment by nathandunn** [comment] 2015-04-10 17:33
@cmdcolin   Can you confirm that this patch is there.  If it is there, assign it to @monicacecilia  to review or assign it to me to push.   Thanks!

**Comment by cmdcolin** [comment] 2015-04-12 17:31
Looks good to me

**Comment by monicacecilia** [comment] 2015-04-14 21:20
Reviewed and working properly. cheers, :heavy_check_mark:

**Closed by monicacecilia** 2015-04-14 21:20 UTC
Labels: Ready
