### ISSUE TITLE
Add "canned attributes" to support a custom Attribute section

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#86] opened 2014-11-20 17:01 UTC
Is there a framework for creating a custom Attribute section?  Attributes are currently completely general, but we could benefit from having a custom tag/value attribute section.  Our current solution is to modify the existing Attribute in order to meet our needs, but it would be much preferable if we could customize it via an Attributes configuration file, either to extend or to create a new set of fields.
I've attached a screenshot of what we are currently working towards. We modified the section name, and constrained the tag so that only one option is usable.

![replace_model_revised2](https://cloud.githubusercontent.com/assets/421248/5128985/c57b532c-70ac-11e4-8f7d-41d1f21cc030.png)

**Comment by nathandunn** [comment] 2015-08-07 16:26
This might be a dupe, but some good notes on it.

**Comment by childers** [comment] 2015-08-07 20:34
Q1: Did this get bumped to a later release?
Q2: Will my code adjustments from the 1.X branches still apply to make this work?  This has been critical to our post-annotation workflow.

**Comment by cmdcolin** [comment] 2015-08-07 21:08
@childers on Q2 which code adjustments are you referring to?

**Comment by nathandunn** [comment] 2015-08-07 21:28
@childers  . . . is this the code where you set the status explicitly based on custom client code?  Then yes, it should not be any different.

**Comment by childers** [comment] 2015-08-07 21:39
I was talking about the "replaced models" custom attribute.

Currently I'm updating the AnnotTrack file directly.

**Comment by nathandunn** [comment] 2015-08-07 21:41
Oh . . you mean this?:

https://github.com/GMOD/Apollo/issues/495 <https://github.com/GMOD/Apollo/issues/495>

Wondering if it should be renamed.  

Nathan

**Comment by childers** [comment] 2015-08-07 23:15
Whoop

**Comment by monicacecilia** [comment] 2016-07-27 21:52
Reorganizing details in this issue for easier tracking. 

-----

Comments from Nathan: 

This is a duplicate of #494  . . .  Basically expand attributes to work like canned comments for attribute key/value pairs.  In the VB and USDA workflow there is need for this.

Todo-list:
- [x] provide canned attribute key values (add CannedAttribute object) similar to CannedComment object
- [x] for each CannedAttribute should provide a list of values.   This could be two tables (CAKey, CAValue)
- [x] create pages to manage
- [x] update "edit" box to incorporate these
- [x] support a "custom attribute" section based on the attribute fields below?

**Comment by monicacecilia** [comment] 2016-07-27 23:32
@nathandunn: 

- I can confirm that I can enter new _Canned Comments_ and new _Canned Values_.

- I am unable to see the result of entering new 'key' terms. The column labeled with the word _Tag_ in the _Attributes_ box of the _Information Editor_ does not reflect these changes. Are you expecting it to appear elsewhere?

**Comment by nathandunn** [comment] 2016-07-27 23:38
This is what I see: 

<img width="346" alt="screen shot 2016-07-27 at 4 36 18 pm" src="https://cloud.githubusercontent.com/assets/751274/17196289/592679b2-5418-11e6-960f-21631c3dcb2b.png">

Perhaps what we mean is "Canned Tag" instead of "Canned Key". 

Also, if you click on the term (please let me know how to improve this interface), you can see that for the Tag, it only shows up for Gene and not MRNA:

<img width="500" alt="screen shot 2016-07-27 at 4 37 49 pm" src="https://cloud.githubusercontent.com/assets/751274/17196330/9c1000c2-5418-11e6-9d88-60c462eabbbd.png">

**Comment by monicacecilia** [comment] 2016-07-27 23:39
OH? That's what I added. But I cannot see it in the same session, despite 'refresh cache' action.

**Comment by erasche** [comment] 2016-07-27 23:42
(just wanted to chime in, this looks great, my older artemis users were asking for something like this since all of our students consistently screwed up spelling the word `Product` with consistent capitalisation ;)

Restricting their answers for product to a CV will be absolutely amazing for our workflows.)

**Comment by nathandunn** [comment] 2016-07-27 23:45
@monicacecilia  Not in the MRNA or the Gene?

**Comment by monicacecilia** [comment] 2016-07-27 23:46
I think it was just upset with me. I can see it now....

**Comment by monicacecilia** [comment] 2016-07-27 23:47
@erasche yay, we're happy to be able to make you guys happy. 😄

**Comment by monicacecilia** [comment] 2016-07-27 23:47
💃 !!

**Closed by monicacecilia** 2016-07-27 23:47 UTC
Labels: enhancement, Important, NAL, Ready
