### ISSUE TITLE
modification of gene models takes too long

### ISSUE THREAD

**Issue by lfaino** [GMOD/Apollo#743] opened 2015-12-18 20:01 UTC
Dear, 
I just installed Apollo 2.0.1 and it works very well. however, modification of loaded gene models takes very long. could you suggest any optimization? the downloading of the gff3 is very slow as well.
I use mysql as database

thanks
Luigi

**Comment by nathandunn** [comment] 2015-12-18 21:14
Mysql should be fine, like all things it might need to be optimized if you have a large group.

WRT to general slowness, memory is a HUGE factor.    I would try doubling your memory (or setting as below) and see if that has any impact on either problem.  How to do it can be found below.  Let us know if you run into any problems with it (this always seems to be the hardest part). 

https://github.com/GMOD/Apollo/blob/master/docs/Troubleshooting.md#tomcat-memory

===

The slow GFF3 is reported in #274  . . . its something that we are aware of.   In the interim, you can try exporting only the scaffolds that have annotations in small groups.   Though, this may also be related to memory.

Let us know if that works.   Thanks.

**Comment by nathandunn** [comment] 2015-12-19 19:16
@lfaino   If increasing the memory doesn't work, please provide additional details about number of annotations and scaffolds and when you do / don't notice problems and any details about the problem (for example "it takes about 3 seconds" to perform to drag the exon boundary). 

We've had good luck with performance testing so far, but we've definitely not looked at every possibility.  

Also keep in mind that we haven't officially released 2.0.1.  Our latest release candidate is 8.   Issue #555 addressed some performance issues when there are multiple edits, but I'm sure that there are other problems.

**Comment by cmdcolin** [comment] 2015-12-19 19:38
In some cases I think this comes back to optimizing usage of the database (i.e. "the N+1 problem" hits us in some cases).

We have been improving in some of those cases but there is more room for improvement I think.

Also, it definitely helps to not use the hot recompile function. This would probably only occur if you were editing the groovy files when doing "apollo run-local" or similar. Need to redeploy if any code changed

**Comment by nathandunn** [comment] 2015-12-20 00:07
I'm wondering, since we'd already done the optimizations in 2.0.0 if the new isoform handling code (correctly re-assigning genes / transcripts when setting boundaries) is causing slow-downs #498 and #73.   I'm sure these could be optimized, but either way there will be a significant number of new checks. 

i.e. ,I'm wondering in cases if the slow-down is pronounced when there are multiple isoforms with lots of exons.  In prior testing I hadn't seen significant slowdowns, but I may have not looked in the right places.

**Comment by nathandunn** [comment] 2015-12-20 00:16
FYI @monicacecilia  . .  if you are testing and have time . . . might help to identify this use-case

**Comment by lfaino** [comment] 2015-12-20 09:36
Dear @nathandunn,
thanks for the answer. I already have a lot of memory allocated to tomcat7. I have 20g. however, I can try to change all the other setting that are mentioned in the link that you sent. we work with fungal genomes with are about 30 Mb and about 11-13 k of genes. for all of them we do not have more than 1000 contigs. 

I know that this is not an official release but the management of the project is much easier. 

I will let you know about detailed slow down.

thanks
Luigi

**Comment by nathandunn** [comment] 2015-12-20 18:21
Hmm . . 20 gb should be way more than enough if running only the Apollo server.  I would estimate that 1-2g max sufficient for that number of scaffolds.   

I guess I would make sure to double-check that it is picking up your memory settings with “ps -ef | grep java"

Are all of the (11-13K) genes loaded as user annotations (in the yellow area at the top) or are they evidence tracks that can be dragged up? 

You should be able to do either, but my guess is that it might be the former.  

Nathan

**Comment by nathandunn** [comment] 2016-01-07 23:42
@lfaino  were you able to figure anything out for this?   Shoot an email me to or on the Apollo lists and we can see if we can't reproduce or resolve this.

**Comment by lfaino** [comment] 2016-01-18 07:37
Hi Nathan,
I double check  java settings and it is 20gb. here the java line:
 /usr/lib/jvm/default-java/bin/java -Djava.util.logging.config.file=/var/lib/tomcat7/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -Xms512m -Xmx20g -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:+UseConcMarkSweepGC -XX:MaxPermSize=1024m -XX:ReservedCodeCacheSize=64m -Djava.endorsed.dirs=/usr/share/tomcat7/endorsed -classpath /usr/share/tomcat7/bin/bootstrap.jar:/usr/share/tomcat7/bin/tomcat-juli.jar -Dcatalina.base=/var/lib/tomcat7 -Dcatalina.home=/usr/share/tomcat7 -Djava.io.tmpdir=/tmp/tomcat7-tomcat7-tmp org.apache.catalina.startup.Bootstrap start

all the genes are loaded in the user annotations. it is incredibly slow when I modify a gene.  

thanks
Luigi

**Comment by nathandunn** [comment] 2016-01-18 16:44
Okay, its probably the genes loaded into the user annotation (which should work).   We’re trying to work on a 2.0.2 release, so this is helpful. 

If you have any data to test with you can email me how to get ahold of it and how private it is: nathandunn@lbl.gov

A few more questions, though:

1 - If you set your max memory to 2 GB’s (instead of 20 GB), does it improve things.  I’m wondering if the system is starved for memory. 
2 - If you only have the gene loaded that you are modifying is it still slow when you make modifications (this might be hard to test)?
3 - Do you have significant overlap of your gene models?   A screen shot might be helpful, if it is information you can share. 

Nathan

**Comment by cmdcolin** [comment] 2016-01-18 16:46
@nathandunn I think this issue would probably be related to what I mentioned at the apollo hackathon, i.e. too many SQL queries

**Comment by lfaino** [comment] 2016-01-18 17:00
Hi nathan,
I work with this fungi:
http://fungi.ensembl.org/Verticillium_dahliaejr2/Info/Index
From the ensembl, you can have a look at the characteristics of the genome.

Currently, we re-sequenced another strain and I`m attending an annotation. 
You could use these information. 
I changed to 2 gb, but it did not improve. Moreover, using PostgreSQL, the annotations were changing very slow as well.

Thanks
Luigi

**Comment by nathandunn** [comment] 2016-01-18 17:43
Thank you.  This is very helpful.

Nathan

**Comment by nathandunn** [comment] 2016-01-18 17:44
Everything on the backend uses sql so I'm guessing you're right ;)

Nathan

**Comment by lfaino** [comment] 2016-01-18 19:37
thanks nathan.
I have a suggestion/observation. I think that the issue is the database. every time that I change a gene model, mysqld starts and takes very long to run. I can monitor using top. 

Luigi

**Comment by nathandunn** [comment] 2016-01-18 21:24
I think what is happening is that one of the operations is querying every feature within a given scaffold (instead of just overlapping ones) which would create this problem. 

On holiday today though so I'll take a look tomorrow.

Nathan

**Comment by lfaino** [comment] 2016-01-18 21:29
one last question... is it an easy fix/modification?

thanks
Luigi

**Comment by nathandunn** [comment] 2016-01-18 23:38
That's my hope.  

I just think we are pulling in too much data when doing the evaluation.  Will try to get it done this week. 

Nathan

**Comment by lfaino** [comment] 2016-01-19 14:06
i was thinking about the problem that you suggested: 
"I think what is happening is that one of the operations is querying every feature within a given scaffold (instead of just overlapping ones) which would create this problem"
this means that if i have a smaller scaffold, the operation would be faster? i can test this on a more scrambled genome.

**Comment by nathandunn** [comment] 2016-01-19 16:26
By smaller, I mean a scaffold with fewer annotated features / transcripts on it, regardless of scaffold length. 

Yes, that would be helpful to test.  

Nathan

**Comment by cmdcolin** [comment] 2016-01-19 17:15
Optimize gff3 export is a different issue (I think #274, and this does definitely suffer the multiple queries per feature slowing it down substantially), but it would be good to know if there are other operations that are slow!

I am currently testing on a organism that has bulk loaded 15000 genes into user-created annotation, but I am not seeing any marked differences in slowdowns of editing gene models compared with an empty user-created annotations track.

**Comment by nathandunn** [comment] 2016-01-19 18:31
@lfaino are you using InnoDB with MySQL (vs MyIsam)?   

If not, you probably should be.   That is the MySQL I'll be testing with.  It handles foreign joins, etc. better, which should improve your performance in this case.   Thanks.

http://stackoverflow.com/questions/12614541/whats-the-difference-between-myisam-and-innodb

**Comment by nathandunn** [comment] 2016-01-19 19:18
@lfaino  I think that the default is InnoDB for MySQL 5.5 or greater.  If you are using something older it might be a problem.  Let us know. 

 https://dev.mysql.com/doc/refman/5.5/en/innodb-default-se.html

**Comment by lfaino** [comment] 2016-01-20 08:32
@nathandunn, the tables show as engine InnoDB. I assume that we use the same version.

about a contig with less features, I have a contig with only few genes (about 10 genes) of length 53kb which is a part of a genome assembly. When I modify a gene model, the time to apply the modification is still very long (about 30 sec or more).

Luigi

**Comment by nathandunn** [comment] 2016-01-20 15:04
Yeah we definitely don't see that.  I'll next with MySQL and get back to you. 

Nathan

**Comment by cmdcolin** [comment] 2016-01-20 15:30
Reminds me of #555 to some extent but I have not seen anything like that in 2.0.1

**Comment by nathandunn** [comment] 2016-01-20 17:48
Initial tests with postgresql and data from here:  http://fungi.ensembl.org/Verticillium_dahliaejr2/Info/Index

I'm using the full 8 chromosomes with many more than 10 operations per feature and many more than 10 features on a single scaffold (8K).  It is very fast, but I am doing this over localhost.  I'm going to send to a remote server and test mysql next.

**Comment by nathandunn** [comment] 2016-01-20 17:48
By fast I mean < 1 sec for most operations (add, set exon boundary, etc.).

**Comment by nathandunn** [comment] 2016-01-20 17:58
Same result on icebox (also PostgreSQL) . . . testing with MySQL next.

**Comment by lfaino** [comment] 2016-01-20 18:18
@nathandunn: how many genes did you load in the annotation track? all of it?

**Comment by lfaino** [comment] 2016-01-20 18:29
@nathandunn: can be the configuration or mysql?

**Comment by nathandunn** [comment] 2016-01-20 18:31
I hadn’t loaded everything yet . . am trying that.  If it still works great then we can do a Skype or something to see what else might be going wrong.   Still testing. 

Nathan

**Comment by lfaino** [comment] 2016-01-20 18:32
Ok. Let me know

**Comment by lfaino** [comment] 2016-01-20 18:32
ok. let me know

**Comment by nathandunn** [comment] 2016-01-20 19:25
My guess is that we are getting a massive slowdown because we are pulling un-necessary attached JSON data in FeatureEvent.  Something to fix.  A typically query like this should be on the order 5-10 ms in this format.   Can confirm that pulling the entire feature_event takes 600 ms whereas takes less than 1.   I have no idea WHY this shows up only when there are a lot of annotations.   Most likely when there are more annotations, the cache memory fills up more so information is more likely to be refetched from the database.     

Can confirm that it is definitely slower EVERYWHERE after loading all of the genes from a single scaffold.   This corresponds with the MySQLd spike.  

select this_.id as id1_21_0_, this_.version as version2_21_0_, this_.child_id as child_id3_21_0_, this_.child_split_id as child_sp4_21_0_, this_.current as current5_21_0_, this_.date_created as date_cre6_21_0_, this_.editor_id as editor_i7_21_0_, this_.last_updated as last_upd8_21_0_, this_.name as name9_21_0_, this_.new_features_json_array as new_fea10_21_0_, this_.old_features_json_array as old_fea11_21_0_, this_.operation as operati12_21_0_, this_.original_json_command as origina13_21_0_, this_.parent_id as parent_14_21_0_, this_.parent_merge_id as parent_15_21_0_, this_.unique_name as unique_16_21_0_ from feature_event this_ where this_.unique_name=? 26874 624 43

select this_.id as id1_21_0_, this_.version as version2_21_0_, this_.child_id as child_id3_21_0_, this_.child_split_id as child_sp4_21_0_, this_.current as current5_21_0_, this_.date_created as date_cre6_21_0_, this_.editor_id as editor_i7_21_0_, this_.last_updated as last_upd8_21_0_, this_.name as name9_21_0_, this_.new_features_json_array as new_fea10_21_0_, this_.old_features_json_array as old_fea11_21_0_, this_.operation as operati12_21_0_, this_.original_json_command as origina13_21_0_, this_.parent_id as parent_14_21_0_, this_.parent_merge_id as parent_15_21_0_, this_.unique_name as unique_16_21_0_ from feature_event this_ where this_.unique_name=? and this_.current=? 17616 629 28




convertJSONToFeature is a subset addFeature . . . addNewFeatureEvent is WAY too high.  



Nathan

**Comment by nathandunn** [comment] 2016-01-20 20:13
So @lfaino , I am seeing the same thing that you are.  I have some ideas, but still trying to figure out why this has to do with scaling, since I would have the same problem. 

Good news / bad news, though.  Guess which one is MySQL and which one is PostgreSQL.   Going to add the same load to PostGreSQL and see where we're at.  

sh ~/test_file.sh  0.02s user 0.01s system 3% cpu 0.630 total
sh ~/test_file.sh  0.00s user 0.01s system 56% cpu 0.019 total

**Comment by nathandunn** [comment] 2016-01-20 20:29
I also don't have an index on that column . . . (unique_name) so that is another obvious culprit).    A b-tree index would easily provide the speed in a simple fetch as seen above.  That is a fetch of a single feature_event (history) based on unique_name, which is our "slow" query.

**Comment by nathandunn** [comment] 2016-01-20 20:41
@lfaino   I think I have a fix for this.  PostgreSQL must add an index of some sort on its own.  When I do it explicitly with MySQL I get a similar speedup.   0.031 (vs 0.630) and nice snappy behavior.  I'll create a pull request shortly.  

https://github.com/nathandunn/Apollo/commit/e278563239a6b8703bf8ec044a228cf7a2ede4bd

**Comment by nathandunn** [comment] 2016-01-20 20:48
Confirmed this works for both PSQL and MySQL.   Awaiting pull request .  .

**Comment by nathandunn** [comment] 2016-01-20 20:49
Test: Confirm that most operations (e.g., set exon boundaries) are quick.

**Comment by lfaino** [comment] 2016-01-20 21:11
So, what should I do? Get again for github?

**Comment by nathandunn** [comment] 2016-01-20 21:15
If you are on master .. You'll have to wait for me to approve the pull request.  However feel free to apply the patch in the commit and see if that works.   The difference should be pretty striking. 

Nathan

**Comment by lfaino** [comment] 2016-01-20 21:18
I will pull tomorrow. Are you going to implement the modification in master?

**Comment by nathandunn** [comment] 2016-01-20 22:37
Yes, I'll push it today.  Just want to review it a bit more.

**Closed** 2016-01-20 23:02 UTC
Labels: Important, optimization, Ready

**Comment by nathandunn** [comment] 2016-01-20 23:28
The change is pushed to master.   Let us know how it works for you.  

Nathan

**Comment by nathandunn** [comment] 2016-01-22 16:17
If you don't see a speed up let us know.  You may have to apply it manually.

**Comment by lfaino** [comment] 2016-01-22 16:26
Hi @nathandunn,
it is better, far better.

thanks
Luigi

**Comment by nathandunn** [comment] 2016-01-22 16:36
:+1:
