### ISSUE TITLE
DraggableAlignments - close, but no CIGAR

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1788] opened 2017-10-14 15:52 UTC
Actually, its incorrect interpretation of CIGAR, but I couldn't resist.

Lets consider the following example:
A long full-transcript BAM read from PacBio IsoSeq protocol.

The read has the following properties:
```
CIGAR: 31M1D48M1I58M1I93M1I39M1I102M1I235M1I18M1I234M1I45M1I11M2I4M1I50M1I63M1I3M1I108M1I33M62N21M1I33M1I22M1I40M1D86M2I16M1I22M1I9M1D17M2I44M1I10M1I187M
MD: 31^A58TG47C27T236G3G3C61G1T16T142A162G20C13CG106GC20C71A16G111T68C7G49^A90C42^C19G196T17C23
```

When this read is promoted to the user created annotations track, the JSON sent by DraggableAlignments track to the server is:
```
{"features":[{"children":[{"location":{"strand":1,"fmin":10112270,"fmax":10112301},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112301,"fmax":10112302},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112302,"fmax":10112350},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112350,"fmax":10112350},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112350,"fmax":10112408},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112408,"fmax":10112408},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112408,"fmax":10112501},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112501,"fmax":10112501},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112501,"fmax":10112540},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112540,"fmax":10112540},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112540,"fmax":10112642},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112642,"fmax":10112642},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112642,"fmax":10112877},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112877,"fmax":10112877},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112877,"fmax":10112895},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112895,"fmax":10112895},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10112895,"fmax":10113129},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113129,"fmax":10113129},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113129,"fmax":10113174},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113174,"fmax":10113174},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113174,"fmax":10113185},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113185,"fmax":10113185},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113185,"fmax":10113189},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113189,"fmax":10113189},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113189,"fmax":10113239},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113239,"fmax":10113239},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113239,"fmax":10113302},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113302,"fmax":10113302},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113302,"fmax":10113305},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113305,"fmax":10113305},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113305,"fmax":10113413},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113413,"fmax":10113413},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113413,"fmax":10113446},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113508,"fmax":10113529},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113529,"fmax":10113529},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113529,"fmax":10113562},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113562,"fmax":10113562},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113562,"fmax":10113584},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113584,"fmax":10113584},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113584,"fmax":10113624},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113624,"fmax":10113625},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113625,"fmax":10113711},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113711,"fmax":10113711},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113711,"fmax":10113727},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113727,"fmax":10113727},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113727,"fmax":10113749},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113749,"fmax":10113749},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113749,"fmax":10113758},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113758,"fmax":10113759},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113759,"fmax":10113776},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113776,"fmax":10113776},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113776,"fmax":10113820},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113820,"fmax":10113820},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113820,"fmax":10113830},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113830,"fmax":10113830},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"strand":1,"fmin":10113830,"fmax":10114017},"type":{"cv":{"name":"sequence"},"name":"exon"}}],"name":"m170602_185518_00127_c101176152550000001823269208081724_s1_p0/3703/1774_65_CCS","location":{"strand":1,"fmin":10112270,"fmax":10114017},"type":{"cv":{"name":"sequence"},"name":"mRNA"}}],"clientToken":"711354549154637597692988837","track":"TTRE_chr2","operation":"add_transcript","username":"deepak.unni3@gmail.com"}
```

Now there are a couple of problems on how DraggableAlignments handles such reads.
Practically, an exon sub-feature should be created when there is a skip (represented with N in the CIGAR string). The current read doesn't have any skips in its CIGAR and yet we see 55 exons as sub-features.

What is actually happening here is that deletions and insertions are being interpreted as an intron/exon boundary.

Lets consider the first three exons with the feature location:
```
{"strand":1,"fmin":10112270,"fmax":10112301}
{"strand":1,"fmin":10112301,"fmax":10112302}
{"strand":1,"fmin":10112302,"fmax":10112350}
```

From the CIGAR string, it is clear that these three exons represent the `31M1D48M` section.

`{"strand":1,"fmin":10112270,"fmax":10112301}` - represents the 31M leading segment before the deletion
`{"strand":1,"fmin":10112301,"fmax":10112302}` - represents the 1D deletion segment
`{"strand":1,"fmin":10112302,"fmax":10112350}` - represents the 48M segment after the deletion

Which explains why we see three exons right next to each other without any introns between them.
And this incorrect interpretation keeps going on and on until the end of the read.

Conclusion:
The CIGAR interpretation logic in DraggableAlignments is incorrect.

**Comment by nathandunn** [comment] 2017-10-16 22:08
@deepakunni3  Should we move this one to another milestone?

**Comment by deepakunni3** [comment] 2017-10-16 22:34
@nathandunn This might take a while to fix. Especially if the bug is native to JBrowse.

**Comment by nathandunn** [comment] 2017-10-16 22:35
Maybe bump this to another milestone and open an issue on the jbrowse GitHub when you have time.

Nathan

**Comment by nathandunn** [comment] 2017-10-17 18:15
Just so we don't forget, seems to be an issue in JBrowse with either the BAM store or LazyFeatures rendering subfeatures between cigar features.

**Comment by nathandunn** [comment] 2017-10-17 19:36
@deepakunni3  I *think* the issue is that here: https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Store/SeqFeature/BAM/LazyFeature.js#L427-L475

Its simply creating subfeatures for EVERYTHING, which is correct visually, but not functionally.   Performance-wise this might also be killer for divs.  

That being said, a couple of options are:
1 - create a single subfeature for a matched region, NOT split up by MDN or X (roughly) with only the minor subfeatures added encompassingly.   So for a read matching from 1-100 with 3 mismatches, there should be one subfeature (E I think) and 3 M subfeatures.   Not sure how / if that would render.  This would be a pure JBrowse fix. 
2 - OR conversely, on the Apollo side, we stitch the read together when creating the annotation.  

Going to start with 1 as it "feels" more correct, but not sure how it might work in practice.

**Comment by deepakunni3** [comment] 2017-10-17 20:22
@nathandunn Good catch! 

Yes, option 1 is the right way to do it while option 2 will be quicker and can be done native to Apollo's client code.

**Comment by nathandunn** [comment] 2017-10-19 14:39
Internal notes: http://localhost/jbrowse/?data=data%2Fwormbase_data&loc=TTRE_MITO%3A3360..3476&tracks=DNA%2CSoftClip%20RNA-Seq%20filtered%20reads%202&highlight=

**Comment by nathandunn** [comment] 2017-10-19 14:47
- https://samtools.github.io/hts-specs/SAMv1.pdf

So, I think the problem is that we are creating a separate subfeatures for M,D,I,X, and cutting up the M/- alignment regions.  Should report the subfeature, but keep a longer underlying feature until we hit an S tag.

- [ ] denote operation for each
- [ ] add test

- https://sites.google.com/site/bioinformaticsremarks/bioinfo/sam-bam-format/what-is-a-cigar
- https://genome.sph.umich.edu/wiki/SAM#What_is_a_CIGAR.3F
- https://www.drive5.com/usearch/manual/cigar.html

**Comment by nathandunn** [comment] 2017-10-19 16:18
From: http://localhost/jbrowse/?data=data%2Fwormbase_data&loc=TTRE_chr2%3A19108683..19108759&tracks=SoftClip%20RNA-Seq%20filtered%20reads%201&highlight=

```
6S28M1D15M1D15M1D5M1D4M2D5M1D26M743N12M1D8M1D5M1D13M1D18M2I8M2I21M57N19M2D25M2D19M1D12M1D6M1D9M1I13M1D7M241N23M2D10M1I21M1D4M1D4M1D6M48N12M1D15M1D11M1D29M1258N12M1D5M1D39M1D39M1D14M1D5M1D8M1D15M1D19M1D34M3D2M53N24M1I9M1I3M2D27M2D9M1D11M1D12M1D6M1D4M1D18M1I9M3D4M1D25M59N17M1I5M1I45M1D34M1D8M2D17M1D8M1D5M1D19M1D16M1D27M1D17M3D328N15M1D9M2D24M1D4M1D4M1D25M3D13M1D13M1D32M1I17M1D5M3D6M1D9M1D5M1D11M1D9M1D101M1D7M3D21M1D31M1I13M1D31M1D13M1D34M1D11M1D6M1D86M1D13M1I6M1I17M1D8M1D9M1D21M1D60M2D12M1D30M1D10M1I39M1D4M1D18M1D14M1D10M1D10M2D29M1D22M1I12M15S
LazyFeature.js:508 231
LazyFeature.js:433 8S26M1D56M743N13M1D14M1D2M1D9M1D31M1D15M57N2M1D9M1D16M1D3M2D80M1D2M241N34M2D24M2D11M48N17M1D13M1D10M1D27M1258N6M1D31M1D78M1D43M1D16M1D23M1D1M53N38M1D10M1D21M1D38M1I38M1I19M2D5M59N11M1D9M1D35M5I11M8I6M1D2M2D12M1I8M1D11M2D21M1D25M1D11M1D8M1D28M1D20M328N15M1I53M1D27M1I12M1I15M1I59M1I58M1I30M1D33M1D7M1D29M1D8M1D5M1D36M2D25M1I20M3D10M1I92M2I15M1D38M1D8M1D6M1D26M1D28M1I71M1I19M1D29M2D36M1D35M1D3M2D11M1D15M1I53M11S
LazyFeature.js:508 168
LazyFeature.js:433 35S6M1I7M2I2M1D58M1I5M743N13M1I36M1D17M2I12M1I10M57N24M1I61M1D32M241N4M1I36M1D26M1I6M48N14M1D7M1I18M1D29M1258N2M3D21M1I6M1D29M1D10M1I10M1D2M1D12M1I4M1I12M1D66M1I16M1D4M1D53N46M1I16M1D25M1I41M1D23M1D7M1D12M59N26M1D52M1D6M1D6M1I80M1I15M1I21M2I22M328N35M2D87M2I27M2D98M1I12M1I3M1I43M1I88M1D6M1I13M164N19M1D5M1D10M1D66M1D33M2I12M1I9M1D10M1I9M1I11M1D34M1D12M1I10M1I18M2D4M1D34M1I8M1D16M1I11M1I38M4S
LazyFeature.js:508 161
LazyFeature.js:433 11S16M1I36M1D8M743N11M1I35M2I7M1I25M1I11M57N3M1I35M1I6M1D43M1I30M241N12M1I10M1I8M7I29M1I14M48N10M1I7M1D43M1I109M1D32M2I12M1D11M1D10M1I13M8I33M1I63M1D13M1I10M1I62M2I11M1D36M1D49M1I18M2I7M1D17M2I8M2I5M1I17M1I13M1D15M1I35M1I5M1I10M1D11M1I22M1I15M2I12M1I54M1I8M1D13M1I42M1D7M1D7M1D5M1I5M1D13M1I35M1D25M2I36M1I28M3I33M1I11M1I6M1I15M1I84M1D7M1I14M1I5M2D11M1D9M1D17M1I7M1I8M1I29M1I22M1I4M1I17M1D4M1D22M1I14M1I15M1I13M1I10M1I13M1I30M1I32M1I14M1I17M1D13M53N7M1D36M1I5M1I13M1D17M1I6M1I14M3I23M1I8M1D6M1D9M1D13M1D11M59N11M1D17M1I13M4I8M1D32M1D11M1D20M1I34M1I14M2I22M1I3M2I18M1I3M2I16M3I5M328N12M1I18M2I11M1I10M1D38M1I13M2I40M1I7M5I30M1I24M1I16M1D6M1D62M1D6M2I36M2I8M2I8M1I24M1D21M2I13M1I4M1I20M6I6M1I7M1D20M1I17M1I9M5I8M3D5M1I4M2I11M1I6M1I18M2I13M2I27M3I19M1I5M2I31M1I7M1I4M1I14M3D9M6I10M1I4M3I6M3I9M1I18M1I31M5I2M1I12M1I7M1D8M2I7M1D18M1I7M1I4M2I12M1D14M1D11M1I25M1I9M1I22M1I8M1I27M15S
LazyFeature.js:508 370
LazyFeature.js:433 7S48M1D10M743N21M1I34M1D33M57N16M1D38M1D38M1I24M241N25M1D47M49D7M1D61M1258N3M2D27M1D22M2D36M1D12M1I53M1D44M53N10M1D69M1I15M2D6M1D20M1D13M1D20M1D14M59N17M1D4M1D19M1D26M1D25M1D12M1D7M1D19M1I5M1I16M1I7M2D48M1D16M328N6M1D3M1D10M1D7M2D9M2D32M1D65M1D4M1D19M1D85M1D32M1D156M2D22M1D26M1D15M1D18M2D18M1D13M1D7M2D22M1D17M1D32M1I34M1D10M1D28M1D30M1D12M1D81M1D26M1D42M1D48M
LazyFeature.js:508 145
LazyFeature.js:433 11S14M1I11M1I7M1D26M743N20M1I15M1I23M1I31M57N23M1I25M1I11M2D11M1D18M2I11M1D4M1I11M241N22M1I8M2D20M1I13M2I8M48N15M1I11M1I44M1258N19M1D17M1D6M1I6M1I14M2I25M1I28M1I7M1D61M1D4M1D4M1D7M50N16M1I9M3I7M1D19M1D16M1D27M1I37M1I36M1I6M1I1M59N13M1D24M1I16M1D40M1I20M1I17M1D9M1I22M1D66M328N97M1I10M7I21M1I3M1I8M3I7M4I53M2I34M1D57M2D9M1D19M1D9M1I16M2I6M2D14M1I8M1I34M2I13M1D19M2D24M1D6M1I25M4I7M6D13M1D28M1D16M1D19M1I34M1D42M1I29M1D25M1I6M1D36M1D27M1D14M1I19M1D11M1I19M1I25M2I18M1I8M1I18M1I21M11S
LazyFeature.js:508 198
GlobalStatsEstimationMixin.js:64 Store statistics: TTRE_all_isoseq.bam {featureDensity: 0.00158447265625, _statsSampleFeatures: 649, _statsSampleInterval: {…}}
LazyFeature.js:433 13S44M743N73M1D15M57N36M1D46M1D31M1D2M241N36M1D36M48N59M1D10M1258N30M1D173M53N68M1D105M59N108M1D64M1I58M328N28M1D416M1D252M1D87M1I166M9S
LazyFeature.js:508 48
LazyFeature.js:433 31S11M1D15M2I13M743N1I4M1I5M2I6M2I19M1I5M1I9M1I20M1I11M1I10M57N2M1I11M1I8M1D12M1D10M1I11M1I12M1I4M1I14M1I9M1I8M1I4M1D10M241N5M3I4M2I16M1I48M48N1M2I13M1D4M3I7M3I19M1D14M3I10M1258N11M1I3M1I8M1I3M1I8M1I6M2I11M3I11M2I23M1I9M1I16M1I55M1I6M1I12M1I10M1I12M53N3M5I9M1I2M2I13M1D7M1I3M7I15M2I23M1I19M1I14M1I14M1I2M2I2M1I14M4I6M1I9M1I18M59N11M3I5M2I10M1I13M1I23M1I24M2I16M1D10M4I9M1I34M2I9M1D9M5I4M1I3M1I9M1I11M1I16M1D12M328N2M1D13M1I19M3I4M1I4M2I11M1I3M1I5M1I9M1I3M2I5M1I11M1D4M1I25M2D7M8I34M1I7M1I4M1D21M2I9M1I7M2I5M1I3M4I12M1I15M1I7M1I3M1I10M2I23M1I6M2I17M1I20M2I22M1I32M1I2M2I6M1D9M5I14M2I13M7I7M6D16M1I13M2I6M1D16M3I5M2I5M1I8M3I6M1I8M2I13M2I12M1I15M2I5M2I5M1I13M1I12M1I17M1I16M1I3M1I18M1I7M1I12M1I3M2I10M2I5M1I5M1I9M1I2M1I21M1I4M1I17M1I8M1I3M1I28M1I6M1I27M1I15M1I17M1I3M1I4M1I22M1I6M1I13M1I9M2I10M3I7M2I10M1D14M14S
LazyFeature.js:508 353
```

vs the original:

```
6S28M1D15M1D15M1D5M1D4M2D5M1D26M743N12M1D8M1D5M1D13M1D18M2I8M2I21M57N19M2D25M2D19M1D12M1D6M1D9M1I13M1D7M241N23M2D10M1I21M1D4M1D4M1D6M48N12M1D15M1D11M1D29M1258N12M1D5M1D39M1D39M1D14M1D5M1D8M1D15M1D19M1D34M3D2M53N24M1I9M1I3M2D27M2D9M1D11M1D12M1D6M1D4M1D18M1I9M3D4M1D25M59N17M1I5M1I45M1D34M1D8M2D17M1D8M1D5M1D19M1D16M1D27M1D17M3D328N15M1D9M2D24M1D4M1D4M1D25M3D13M1D13M1D32M1I17M1D5M3D6M1D9M1D5M1D11M1D9M1D101M1D7M3D21M1D31M1I13M1D31M1D13M1D34M1D11M1D6M1D86M1D13M1I6M1I17M1D8M1D9M1D21M1D60M2D12M1D30M1D10M1I39M1D4M1D18M1D14M1D10M1D10M2D29M1D22M1I12M15S
LazyFeature.js:473 222
LazyFeature.js:432 8S26M1D56M743N13M1D14M1D2M1D9M1D31M1D15M57N2M1D9M1D16M1D3M2D80M1D2M241N34M2D24M2D11M48N17M1D13M1D10M1D27M1258N6M1D31M1D78M1D43M1D16M1D23M1D1M53N38M1D10M1D21M1D38M1I38M1I19M2D5M59N11M1D9M1D35M5I11M8I6M1D2M2D12M1I8M1D11M2D21M1D25M1D11M1D8M1D28M1D20M328N15M1I53M1D27M1I12M1I15M1I59M1I58M1I30M1D33M1D7M1D29M1D8M1D5M1D36M2D25M1I20M3D10M1I92M2I15M1D38M1D8M1D6M1D26M1D28M1I71M1I19M1D29M2D36M1D35M1D3M2D11M1D15M1I53M11S
LazyFeature.js:473 159
LazyFeature.js:432 35S6M1I7M2I2M1D58M1I5M743N13M1I36M1D17M2I12M1I10M57N24M1I61M1D32M241N4M1I36M1D26M1I6M48N14M1D7M1I18M1D29M1258N2M3D21M1I6M1D29M1D10M1I10M1D2M1D12M1I4M1I12M1D66M1I16M1D4M1D53N46M1I16M1D25M1I41M1D23M1D7M1D12M59N26M1D52M1D6M1D6M1I80M1I15M1I21M2I22M328N35M2D87M2I27M2D98M1I12M1I3M1I43M1I88M1D6M1I13M164N19M1D5M1D10M1D66M1D33M2I12M1I9M1D10M1I9M1I11M1D34M1D12M1I10M1I18M2D4M1D34M1I8M1D16M1I11M1I38M4S
LazyFeature.js:473 151
LazyFeature.js:432 11S16M1I36M1D8M743N11M1I35M2I7M1I25M1I11M57N3M1I35M1I6M1D43M1I30M241N12M1I10M1I8M7I29M1I14M48N10M1I7M1D43M1I109M1D32M2I12M1D11M1D10M1I13M8I33M1I63M1D13M1I10M1I62M2I11M1D36M1D49M1I18M2I7M1D17M2I8M2I5M1I17M1I13M1D15M1I35M1I5M1I10M1D11M1I22M1I15M2I12M1I54M1I8M1D13M1I42M1D7M1D7M1D5M1I5M1D13M1I35M1D25M2I36M1I28M3I33M1I11M1I6M1I15M1I84M1D7M1I14M1I5M2D11M1D9M1D17M1I7M1I8M1I29M1I22M1I4M1I17M1D4M1D22M1I14M1I15M1I13M1I10M1I13M1I30M1I32M1I14M1I17M1D13M53N7M1D36M1I5M1I13M1D17M1I6M1I14M3I23M1I8M1D6M1D9M1D13M1D11M59N11M1D17M1I13M4I8M1D32M1D11M1D20M1I34M1I14M2I22M1I3M2I18M1I3M2I16M3I5M328N12M1I18M2I11M1I10M1D38M1I13M2I40M1I7M5I30M1I24M1I16M1D6M1D62M1D6M2I36M2I8M2I8M1I24M1D21M2I13M1I4M1I20M6I6M1I7M1D20M1I17M1I9M5I8M3D5M1I4M2I11M1I6M1I18M2I13M2I27M3I19M1I5M2I31M1I7M1I4M1I14M3D9M6I10M1I4M3I6M3I9M1I18M1I31M5I2M1I12M1I7M1D8M2I7M1D18M1I7M1I4M2I12M1D14M1D11M1I25M1I9M1I22M1I8M1I27M15S
LazyFeature.js:473 362
LazyFeature.js:432 7S48M1D10M743N21M1I34M1D33M57N16M1D38M1D38M1I24M241N25M1D47M49D7M1D61M1258N3M2D27M1D22M2D36M1D12M1I53M1D44M53N10M1D69M1I15M2D6M1D20M1D13M1D20M1D14M59N17M1D4M1D19M1D26M1D25M1D12M1D7M1D19M1I5M1I16M1I7M2D48M1D16M328N6M1D3M1D10M1D7M2D9M2D32M1D65M1D4M1D19M1D85M1D32M1D156M2D22M1D26M1D15M1D18M2D18M1D13M1D7M2D22M1D17M1D32M1I34M1D10M1D28M1D30M1D12M1D81M1D26M1D42M1D48M
LazyFeature.js:473 137
LazyFeature.js:432 11S14M1I11M1I7M1D26M743N20M1I15M1I23M1I31M57N23M1I25M1I11M2D11M1D18M2I11M1D4M1I11M241N22M1I8M2D20M1I13M2I8M48N15M1I11M1I44M1258N19M1D17M1D6M1I6M1I14M2I25M1I28M1I7M1D61M1D4M1D4M1D7M50N16M1I9M3I7M1D19M1D16M1D27M1I37M1I36M1I6M1I1M59N13M1D24M1I16M1D40M1I20M1I17M1D9M1I22M1D66M328N97M1I10M7I21M1I3M1I8M3I7M4I53M2I34M1D57M2D9M1D19M1D9M1I16M2I6M2D14M1I8M1I34M2I13M1D19M2D24M1D6M1I25M4I7M6D13M1D28M1D16M1D19M1I34M1D42M1I29M1D25M1I6M1D36M1D27M1D14M1I19M1D11M1I19M1I25M2I18M1I8M1I18M1I21M11S
LazyFeature.js:473 189
LazyFeature.js:432 13S44M743N73M1D15M57N36M1D46M1D31M1D2M241N36M1D36M48N59M1D10M1258N30M1D173M53N68M1D105M59N108M1D64M1I58M328N28M1D416M1D252M1D87M1I166M9S
LazyFeature.js:473 39
LazyFeature.js:432 31S11M1D15M2I13M743N1I4M1I5M2I6M2I19M1I5M1I9M1I20M1I11M1I10M57N2M1I11M1I8M1D12M1D10M1I11M1I12M1I4M1I14M1I9M1I8M1I4M1D10M241N5M3I4M2I16M1I48M48N1M2I13M1D4M3I7M3I19M1D14M3I10M1258N11M1I3M1I8M1I3M1I8M1I6M2I11M3I11M2I23M1I9M1I16M1I55M1I6M1I12M1I10M1I12M53N3M5I9M1I2M2I13M1D7M1I3M7I15M2I23M1I19M1I14M1I14M1I2M2I2M1I14M4I6M1I9M1I18M59N11M3I5M2I10M1I13M1I23M1I24M2I16M1D10M4I9M1I34M2I9M1D9M5I4M1I3M1I9M1I11M1I16M1D12M328N2M1D13M1I19M3I4M1I4M2I11M1I3M1I5M1I9M1I3M2I5M1I11M1D4M1I25M2D7M8I34M1I7M1I4M1D21M2I9M1I7M2I5M1I3M4I12M1I15M1I7M1I3M1I10M2I23M1I6M2I17M1I20M2I22M1I32M1I2M2I6M1D9M5I14M2I13M7I7M6D16M1I13M2I6M1D16M3I5M2I5M1I8M3I6M1I8M2I13M2I12M1I15M2I5M2I5M1I13M1I12M1I17M1I16M1I3M1I18M1I7M1I12M1I3M2I10M2I5M1I5M1I9M1I2M1I21M1I4M1I17M1I8M1I3M1I28M1I6M1I27M1I15M1I17M1I3M1I4M1I22M1I6M1I13M1I9M2I10M3I7M2I10M1D14M14S
LazyFeature.js:473 344
```

**Comment by nathandunn** [comment] 2017-10-19 18:37
After some discussion with @deepakunni3  we decided that this should really be fixed on the Apollo side, so we will stitch together subfeatures for this as they come in (on the client-side) if they are abutting.

**Comment by nathandunn** [comment] 2019-02-08 23:43
From #2036   

Following on from #2034, it would be hugely helpful if split reads would create features with introns.

Ideally, dragging a read spanning an (implied) intron to the User-created annotations track would create a new annotation (or add CDS features to an existing annotation) that did not include the gapped bases.

This is an example of the undesired behaviour as of 5a3cde3ee1232833c333186cbc0d7f997716e64a:

![webapollo-bug-report-2019-02-07_16 37 01](https://user-images.githubusercontent.com/31576/52446453-12614300-2afc-11e9-9607-00be8deb0181.gif)

**Comment by nathandunn** [comment] 2019-02-08 23:44
FYI @robsyme . closing #2036 in favor of this

**Closed** 2019-02-11 19:50 UTC
Labels: bug, in progress
