### ISSUE TITLE
Current organism, addStores and addTracks information lost when clicking "Show Annotator Panel"

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1156] opened 2016-07-01 14:32 UTC
This might be similar or related to issue #1140,  #1141;  loadLink not passing all parameters through, but when I try to pass addStores and addTracks information through to the new Apollo2 view (via the Show Annotator Panel) the information from my current view is completely lost.  I lose the organism I was working on, and the track and datastore are also lost once I load the organism.  

/apollo-2.0.3/Tigriopus californicus/jbrowse/?loc=scaffold_222%3A147374..147857&addStores={"url"%3A{"type"%3A"JBrowse%2FStore%2FSeqFeature%2FGFF3"%2C"urlTemplate"%3A"https%3A%2F%2Fgmod-dev.server%2Fwebapp%2Fmedia%2Fblast%2Ftask%2F8796ff4bad7b4dd6b15237abc9bd0cc3%2FTCALIF_genome_v1.0_new_ids.fasta.gff"}}&addTracks=[{"label"%3A"BLAST%2B Results"%2C"category"%3A"0. Reference Assembly"%2C"type"%3A"WebApollo%2FView%2FTrack%2FDraggableBLASTFeatures"%2C"store"%3A"url"%2C"style"%3A{"renderClassName"%3A"gray-center-10pct"%2C"subfeatureClasses"%3A{"match_part"%3A"blast-match_part"}}}]&tracks=DNA%2CAnnotations%2CBLAST%2B Results&highlight=

**Comment by nathandunn** [comment] 2016-07-01 17:09
Looks like I am forgetting to copy it in the link, but it makes sense.

**Comment by nathandunn** [comment] 2016-07-01 18:51
Use-cases:

- [ ] logged out and viewing a public genome and click "Annotator Panel" (uses the clientToken instead of the organism ID)
- [ ] logged in and clicking on "Annotator Panel" passes token, but not the organism

**Comment by nathandunn** [comment] 2016-07-05 21:28
I'm pulling the comment off of #1156 from @childers

> Looking at the dev console, I think it is passing the right information, but I'm not sure why it isn't directing the browser to load the proper scaffold. The HSP is on scaffold_173, and going form the BLAST output to Jbrowse/Apollo-classic mode works fine. When I click the button it displays scaffold_1022. Check out the image for more information.

<img width="1335" alt="apollo2 0 4-incorrect_redirect" src="https://cloud.githubusercontent.com/assets/421248/16586306/29aaba72-4293-11e6-98e9-5ba2cee78838.png">

**Comment by nathandunn** [comment] 2016-07-05 21:33
@childers  I'm trying to clarify what you were doing.  

I'm reading it as: 
1 - click blast link.  Expected: Link to proper scaffold occurs with dynamic track.  Actual == expected 
2 - While on that blast link, go to another scaffold.  Expected: Goes to the selected scaffold.  Actual: Goes to a random scaffold.  ?? 

It looks like there is something really screwed up in the query string, but I'm trying to figure out how it gets into this state.    I'm assuming you get the same behavior in Chrome or Firefox.

**Comment by childers** [comment] 2016-07-06 13:22
@nathandunn halfway right.
1 - click BLAST link, Jbrowse/Apollo-classic mode (do you have proper names for the classic/paneled views?) displays as normal. - > if I click on the "Show Annotator Panel" It takes me to a random scaffold.  The developer panel imaga above shows that it is sending the loc value to the proper scaffold. Since it is passing the right scaffold name, I don't understand why it is redirecting somewhere else.  

2 - If I go back to the BLAST results and click another HSP on another scaffold, it behaves as in (1).

**Comment by childers** [comment] 2016-07-06 13:24
1) I'll wipe my repo and do a clean clone off master since the changes are in it now.
2) I'll also create a new database in case there is something weird about the schema being from an earlier apollo2 release. 

I'll update once it's all together and I've had a chance to test it a few times.

**Comment by nathandunn** [comment] 2016-07-06 18:44
/Tigriopus%20californicus/jbrowse/?loc=scaffold_173%3A215514..215948&addStores=%7B"url"%3A%7B"type"%3A"JBrowse%2FStore%2FSeqFeature%2FGFF3"%2C"urlTemplate"%3A"https%3A%2F%2Fgmod-dev.nal.usda.gov%2Fwebapp%2Fmedia%2Fblast%2Ftask%2F840d15063f164f28909c423561a94ad7%2FTCALIF_genome_v1.0_new_ids.fasta.gff"%7D%7D&addTracks=%5B%7B"label"%3A"BLAST%2B%20Results"%2C"category"%3A"0.%20Reference%20Assembly"%2C"type"%3A"WebApollo%2FView%2FTrack%2FDraggableBLASTFeatures"%2C"store"%3A"url"%2C"style"%3A%7B"renderClassName"%3A"gray-center-10pct"%2C"subfeatureClasses"%3A%7B"match_part"%3A"blast-match_part"%7D%7D%7D%5D&tracks=DNA%2CAnnotations%2CBLAST%2B%20Results&highlight=

**Comment by nathandunn** [comment] 2016-07-06 18:44
Clicking on the Annotator Panel seems to set the wrong scaffold.

**Comment by nathandunn** [comment] 2016-07-06 18:48
In the preferences, that seems pretty straight-forward, unless it is parsing incorrectly. 

@childers  Let me know if you saw anything in the error logs.

**Comment by childers** [comment] 2016-07-06 20:03
Well, at first it seemed pretty nonchalant, then it threw some errors:
``` shell
setting other orgs false for 136473700866522560756
2016-07-06 16:01:58,025 [http-nio-8080-exec-9] ERROR errors.GrailsExceptionResolver  - IOException occurred when processing request: [GET] /apollo-2.0.4-SNAPSHOT/136473700866522560756/jbrowse/plugins/WebApollo/img/loading.gif
Broken pipe. Stacktrace follows:
java.io.IOException: Broken pipe
	at org.bbop.apollo.JbrowseController.passthrough(JbrowseController.groovy:488)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-07-06 16:01:58,032 [http-nio-8080-exec-9] ERROR errors.GrailsExceptionResolver  - IllegalStateException occurred when processing request: [GET] /apollo-2.0.4-SNAPSHOT/136473700866522560756/jbrowse/plugins/WebApollo/img/loading.gif
getOutputStream() has already been called for this response. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at java.io.FilterWriter.flush(FilterWriter.java:100)
	... 12 more
```

**Comment by childers** [comment] 2016-07-06 20:20
in localhost.2016-07-06.log:

``` shell
06-Jul-2016 16:01:58.034 SEVERE [http-nio-8080-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [/apollo-2.0.4-SNAPSHOT] threw exception [org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response] with root cause
 java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:578)
...
...
...
```

**Comment by nathandunn** [comment] 2016-07-06 20:24
Hmm . . none of those are serious.  Was looking more for parse errors.  I’ll take a look and see.

**Comment by nathandunn** [comment] 2016-07-06 21:49
Hmm . . I'm having trouble reproducing these.   My guesses are:
1 - old code  (unlikely)
2 - its pulling a scaffold ID from another organism (without that scaffold) and so it just picks one at random
3 - something in the loadLink screen is causing issues. 

@childers  
If you get rid of the extra store data in the link, does it cause problems? 

e.g., if you put an alert before this final string, what do you get when you click on "Show Annotator Panel"? 

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/main.js#L444

**Comment by childers** [comment] 2016-07-07 13:27
I'm creating and populating an entirely new database to test this with.

**Comment by monicacecilia** [comment] 2016-07-28 00:21
@nathandunn ok. Thanks for updating the milestone. 👍

**Comment by childers** [comment] 2016-08-19 20:18
Testing this with the 2.0.4 release patched with pr #1216 

When I click on Show Annotator Panel, it still redirects me to a different scaffold, though it does transmit the added track and proper organism.

<img width="1365" alt="apollo-redirect-before" src="https://cloud.githubusercontent.com/assets/421248/17823048/9fabb93e-6628-11e6-8553-82b59a04ba57.png">
<img width="1365" alt="apollo-redirect-after" src="https://cloud.githubusercontent.com/assets/421248/17823050/9fb224a4-6628-11e6-85b3-18eab1fe3887.png">

**Comment by nathandunn** [comment] 2016-08-19 23:12
- [ ] outstanding issue with when switching back and forth #1214

**Comment by nathandunn** [comment] 2016-08-31 18:43
So, to get this to occur:
1 - login to Apollo in full-screen mode 
2 - click on JBrowse link from blast with the addStore  . .. goes to where it is expected
3 - click on the annotator panel link and always chooses the same (WRONG) one

**Comment by nathandunn** [comment] 2016-08-31 18:46
When logged out, the show annotator panel link also fails.

**Comment by nathandunn** [comment] 2016-09-01 16:40
The issue is that when you go to the organism in JBrowse view you can a URL like this when logged in where the client_token is "Honey2", which is not good:

| 195 |       0 | Honey2                        | 2016-09-01 09:37:45 | NULL   | 2016-09-01 09:37:45 | NULL | NULL               | org.bbop.apollo.UserOrganismPreference |       1 |                1 |    NULL |              NULL |           3 |        5647 |    NULL |

What should happen is that if you are logged in, it should always have a client_token that is not an organism and redirect.

**Comment by nathandunn** [comment] 2016-09-01 16:49
e.g. string: ```http://localhost:8080/apollo/3/jbrowse/index.html?loc=Group1.5%3A78988..606820&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2&highlight=```

**Comment by nathandunn** [comment] 2016-09-01 17:13
Closing in favor of #1214

**Closed by nathandunn** 2016-09-01 17:13 UTC
Labels: blocked, Workingon
