### ISSUE TITLE
Deleting multiple isoforms can produce exception

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#874] opened 2016-02-12 18:59 UTC
If you try and delete multiple isoforms in succession, it can produce something probably like a race condition and cause an error. 

```
| Error 2016-02-12 12:50:26,651 [clientInboundChannel-4] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
Message: Object of class [org.bbop.apollo.Gene] with identifier [60604]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.Gene#60604]
    Line | Method
->>  172 | $tt__removeFeatureRelationship in org.bbop.apollo.FeatureRelationshipService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1874 | $tt__deleteFeature             in org.bbop.apollo.RequestHandlingService
|   1135 | doCall . . . . . . . . . . . . in org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4_closure5_closure6
|   1134 | doCall                         in org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4_closure5
|   1130 | doCall . . . . . . . . . . . . in org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4
|    289 | call                           in groovyx.gpars.group.PGroup$3
|    313 | run . . . . . . . . . . . . .  in groovyx.gpars.group.PGroup$4
|   1145 | runWorker                      in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run                            in java.lang.Thread
Caused by StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.Gene#60604]
->>  172 | $tt__removeFeatureRelationship in org.bbop.apollo.FeatureRelationshipService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1874 | $tt__deleteFeature             in org.bbop.apollo.RequestHandlingService
|   1135 | doCall . . . . . . . . . . . . in org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4_closure5_closure6
|   1134 | doCall                         in org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4_closure5
|   1130 | doCall . . . . . . . . . . . . in org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4
|    289 | call                           in groovyx.gpars.group.PGroup$3
|    313 | run . . . . . . . . . . . . .  in groovyx.gpars.group.PGroup$4
|   1145 | runWorker                      in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run                            in java.lang.Thread
```

This also leads to that feature not being deleted. The user can go and try again to delete it but they are not notified that any error occurred deleting their feature either.

**Comment by cmdcolin** [comment] 2016-02-12 20:56
I was a little surprised by this because RequestHandlingService is marked as @Transactional

Maybe we have to trigger a flush somewhere for the deletion. Not sure

**Comment by nathandunn** [comment] 2016-02-15 18:48
I am unable to reproduce it.   Any ideas how to do this consistently?

**Comment by cmdcolin** [comment] 2016-02-15 19:26
This happens specifically when deleting multiple isoforms, so, it's not from random nonoverlapping features. If you would had many isoforms of a gene in the annotator track and then deleted those isoforms with shift-select+delete, then I can normally see it happen

**Comment by nathandunn** [comment] 2016-02-15 21:50
I can't seem to reproduce this on staging with about 8 isoforms and clicking fairly quickly.

**Comment by monicacecilia** [comment] 2016-02-19 17:59
I have tried this as well: both trying to delete just several copies of the same isoform as well as trying to delete different isoforms for the same gene, and I have not been able to reproduce this error either.

**Comment by nathandunn** [comment] 2016-02-19 18:00
Okay . . let's close this for now and we can reopen later if needbe.   Sometimes websockets, etc. get confused during development.

I think that possibly @cmdcolin  other performance improvements and the newer widgets that @deepakunni3  may have made this much harder to reproduce.

**Closed by nathandunn** 2016-02-19 18:00 UTC
Labels: bug

**Comment by cmdcolin** [comment] 2016-02-19 18:24
Sounds ok to me. Not being produced on Apollo-staging for example but it's pretty easily produced on my local dev machine.

**Comment by nathandunn** [comment] 2016-02-19 18:30
I wonder if its something to do with web sockets or badly cached code.    The possibilities would be:

1 - a bug in our merge / isoform code when handling genes
2 - bad data in your local machine
3 - a problem with web sockets updating locally (and trying to handle things that are in a different state)
4 - the code is cached funny
5 - a timing error WRT to web sockets and the backend

I think that only 1 and 5 are legitimate bugs we can fix.  I would try duplicating the organism you are on and seeing if you can’t replicate the problem with new annotations.  Of course, then how you got into that funky state would be interesting to note as well.

Nathan
