### ISSUE TITLE
(1d) Jbrowse only mode to display "public" links

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#353] opened 2015-05-07 15:57 UTC
Is there documentation describing how to run this in browser (not logged in) mode?

**Comment by nathandunn** [comment] 2015-05-07 16:25
See AnnotationController::loadLink() . . takes OrganismId and sets Organism preference

**Comment by nathandunn** [comment] 2015-05-07 17:29
From the GuestTag class, like in the other example, I think that a guest won't have a principal (and so it returns true if no principal):

      if(this.getSubject() != null && this.getSubject().getPrincipal() != null) {
            return 0;
        } else {
            return 1;
        }

You can get the Shiro session this way (which I believe wraps HttpSession):

        Session session = SecurityUtils.subject.session(false)

Currently we allow guests to access everything, but the GWT sort of blocks that.

**Comment by nathandunn** [comment] 2015-05-08 23:51
@cmdcolin  This was important so that we could copy / paste "public" links but serve the out of JBrowse (without annotation).  Just an FYI . . I kept forgetting why this was important.

**Comment by nathandunn** [comment] 2015-05-08 23:52
of course . . you could do the same thing with Mod_proxy as well, though defeats the ease-of-use /setup.

**Comment by selewis** [comment] 2015-05-09 00:02
I'd don't think it was important. As I recall it was so that someone could
effectively share a sneak peak in a read-only mode with someone. At the
time there was no way to use apollo in read-only mode, it was solely
visible in edit mode.

The JBrowse solution was unsatisfactory because person who got the link
still couldn't see the (read-only) the annotation track.

**Comment by nathandunn** [comment] 2015-05-09 00:08
So I can move the "Important" label?     If a user is give "read-only" permissions they have to log-in and they will be in read-only mode.    

At some point we want to have a "public" group / permissions for tracks and annotations (i.e., not requiring a login).   A JBrowse link (in the old style) essentially makes all Tracks public, but not UcA. 

@monicacecilia  had some thoughts on this as well I know.

**Comment by selewis** [comment] 2015-05-09 00:26
If it's read-only why do they need to login?

**Comment by nathandunn** [comment] 2015-05-09 01:06
Because its not public.  People may not choose to share their evidence or annotations.  

We definitely need to handle both cases (public and read-only at track and organism level).   Just trying to determine what is important for 2.0.0.  My intuition is that jbrowse public-only is important for 2.0.0, but I am not a user.  

Nathan

**Comment by selewis** [comment] 2015-05-09 02:14
Got it.

I agree, both public and shared are needed (with login for shared, but if
the person is already invited and they've already logged in then they
shouldn't need to re-login just for that particular view)

**Comment by nathandunn** [comment] 2015-06-04 23:04
Mostly working . .. when logged out, still loadding the AnnotTrack . . . not sure why.

**Comment by nathandunn** [comment] 2015-06-05 00:53
The only thing that is not working is that when logged out that it is still showing the AnnoTrack.js (and trying to load features, which of course fails).  

I’m wondering if there is a check I’m missing to tell it that I’m logged out, or if I’m just returning the wrong thing (or its throwing a 500 error when it should be catching it).

**Comment by nathandunn** [comment] 2015-06-08 13:35
For this query:  { "track": "Annotations-Group1.1", "operation": "get_user_permission" }:
In WA2 I return 200:  {"operation":"get_user_permission","track":"Annotations-Group1.1","permission":0}
In WA1 it returns 400:  {"error":"You must first login before editing"}

**Comment by cmdcolin** [comment] 2015-06-08 14:13
Sweet. looks good. I was slightly concerned because even if you did log in, it doesn't work yet, but within the scope of this problem it's pretty good. Could either redirect them to annotator panel after login or allow editing without the annotator panel

**Comment by nathandunn** [comment] 2015-06-08 14:17
Hmm . . it does work for me if you log-in.  The only issue is that if you hit "full-screen" mode it doesn't know the organism, but that should be fixed in #319.

**Comment by cmdcolin** [comment] 2015-06-08 15:09
It does work at least on a basic level, but the problem with the login is that the web socket doesn't work, because the web socket is assuming the annotator panel exists (does window.parent call)

**Comment by nathandunn** [comment] 2015-06-08 15:32
Is the websocket needed for anything when logged out?  I can still disable the call. 

Nathan

**Comment by cmdcolin** [comment] 2015-06-08 16:10
you don't necessarily have to disable anything, I mean, let me see if I can find a workaround...

**Comment by nathandunn** [comment] 2015-06-08 16:20
K . .  the code should be checking for window.parent to see if it even exists prior to opening a websocket connection to the server:

```
  if (typeof window.parent.getEmbeddedVersion == 'function') {
                        if (window.parent.getEmbeddedVersion() == 'ApolloGwt-2.0') {
    // . . . . 
    client.connect( {}, function() {
```

So, I end up not getting a websocket error at all.   Just that its choosing the wrong organism.

Did you try using:

```./scripts/copy_client.sh  ```

To make sure its updating the client code?

**Comment by cmdcolin** [comment] 2015-06-08 16:27
The thing that I am mentioning is that it is allowing you to login, but it won't setup the websocket due to the code that you are mentioning. Therefore, it allows you to create annotations but you won't see any feedback

**Comment by nathandunn** [comment] 2015-06-08 16:32
I see.   If you are logged in, but are not using the AnnotatorPanel.  I think you are going to have to solve it as part of #319, since you'll need a way to persist organism without getting it from the parent. 

````
client.connect({}, function () {
@someuser, etc.
                                var organism = JSON.parse(window.parent.getCurrentOrganism());
                                var sequence = JSON.parse(window.parent.getCurrentSequence());
                                client.subscribe("/topic/AnnotationNotification/" + organism.id + "/" + sequence.id, function (message) {
                                    var changeData;
```

**Comment by monicacecilia** [comment] 2015-06-25 18:12
@nathandunn 
"JBrowse mode only" does NOT work if user is logged into Apollo with the "annotator" side panel enabled. 
It works only if the user is on the "Full-screen"view. 
Is this the intended behavior?

**Comment by nathandunn** [comment] 2015-06-25 18:45
Yes!

**Comment by cmdcolin** [comment] 2015-06-25 19:38
I think that is currently the intended mode of operation for "JBrowse only mode", is to have the user browse only the tracks without having the annotator side panel.

Interestingly, it does work if you login into this mode, and then you can create annotations very similar to 1.0, but the main goal is to just provide the jbrowse only mode.

**Comment by nathandunn** [comment] 2015-06-26 19:29
@monicacecilia   Can this be closed?

**Comment by monicacecilia** [comment] 2015-06-26 19:31
yes @cmdcolin that is the intention. 

and yes @nathandunn, closed it is. :dancer:

**Closed by monicacecilia** 2015-06-26 19:31 UTC
Labels: discussion, Important, Ready
