### ISSUE TITLE
Overlapper issue 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#34] opened 2014-10-06 22:13 UTC
- Overlapper issue - Not sure what the deal is, but it might be worth noting that we're using the November 2013 WA version for this particular genome (didn't want to deal with updating issues while people were actively annotating).

**Comment by nathandunn** [comment] 2015-04-06 03:16
Probably just need to double-check or clarify.

**Comment by monicacecilia** [comment] 2015-04-08 17:57
Unable to reproduce this. 
Should it arise again after 2.0, let's bring it back. I'm closing for now.

**Closed by monicacecilia** 2015-04-08 17:57 UTC
Labels: Ready
